/** Execution photos for each exercise: two frames (start / end position)
 * from Free Exercise DB (github.com/yuhonas/free-exercise-db), released
 * into the public domain under the Unlicense. Files live in
 * public/fit/exercicios/<source id>/{0,1}.webp — see
 * scripts/fit-download-images.mjs.
 *
 * `approx: true` means the photo shows the same movement with a different
 * implement (e.g. cable instead of elastic band); the UI says so. Exercises
 * missing here fall back to the illustrated tile. */
export const EXERCISE_IMAGES: Record<string, { src: string; approx?: boolean }> = {
  // Peito
  flexao: { src: "Pushups" },
  flexao_inclinada: { src: "Incline_Push-Up" },
  flexao_declinada: { src: "Decline_Push-Up" },
  flexao_explosiva: { src: "Plyo_Push-up" },
  flexao_diamante: { src: "Pushups_Close_and_Wide_Hand_Positions" },
  supino_halteres: { src: "Dumbbell_Bench_Press" },
  supino_halteres_chao: { src: "Dumbbell_Floor_Press" },
  supino_inclinado_halteres: { src: "Incline_Dumbbell_Press" },
  supino_barra: { src: "Barbell_Bench_Press_-_Medium_Grip" },
  supino_maquina: { src: "Machine_Bench_Press" },
  crucifixo_halteres: { src: "Dumbbell_Flyes" },
  crossover: { src: "Cable_Crossover" },
  crucifixo_elastico: { src: "Cross_Over_-_With_Bands" },
  mergulho_paralelas: { src: "Dips_-_Chest_Version" },
  flexao_trx: { src: "Suspended_Push-Up" },
  peck_deck: { src: "Butterfly" },
  supino_inclinado_maquina: { src: "Leverage_Incline_Chest_Press" },
  crossover_baixo: { src: "Low_Cable_Crossover" },
  supino_smith: { src: "Smith_Machine_Bench_Press" },
  supino_inclinado_smith: { src: "Smith_Machine_Incline_Bench_Press" },
  // Costas
  barra_fixa: { src: "Pullups" },
  barra_supinada: { src: "Chin-Up" },
  barra_negativa: { src: "Pullups" },
  barra_elastico: { src: "Band_Assisted_Pull-Up" },
  puxada_frente: { src: "Wide-Grip_Lat_Pulldown" },
  puxada_elastico: { src: "Wide-Grip_Lat_Pulldown", approx: true },
  remada_curvada_barra: { src: "Bent_Over_Barbell_Row" },
  remada_unilateral: { src: "One-Arm_Dumbbell_Row" },
  remada_curvada_halteres: { src: "Bent_Over_Two-Dumbbell_Row" },
  remada_baixa: { src: "Seated_Cable_Rows" },
  remada_elastico: { src: "Seated_Cable_Rows", approx: true },
  remada_invertida: { src: "Inverted_Row" },
  superman: { src: "Superman" },
  pulldown_braco_estendido: { src: "Straight-Arm_Pulldown" },
  kb_remada: { src: "One-Arm_Kettlebell_Row" },
  puxada_supinada: { src: "Underhand_Cable_Pulldowns" },
  puxada_triangulo: { src: "V-Bar_Pulldown" },
  remada_articulada: { src: "Leverage_Iso_Row" },
  puxada_articulada: { src: "Leverage_High_Row" },
  remada_unilateral_polia: { src: "Seated_One-arm_Cable_Pulley_Rows" },
  remada_smith: { src: "Smith_Machine_Bent_Over_Row" },
  hiperextensao: { src: "Hyperextensions_Back_Extensions" },
  // Ombros
  desenvolvimento_halteres: { src: "Dumbbell_Shoulder_Press" },
  desenvolvimento_barra: { src: "Standing_Military_Press" },
  desenvolvimento_maquina: { src: "Machine_Shoulder_Military_Press" },
  desenvolvimento_elastico: { src: "Shoulder_Press_-_With_Bands" },
  desenvolvimento_smith: { src: "Smith_Machine_Overhead_Shoulder_Press" },
  kb_press: { src: "Alternating_Kettlebell_Press" },
  elevacao_lateral: { src: "Side_Lateral_Raise" },
  elevacao_lateral_elastico: { src: "Lateral_Raise_-_With_Bands" },
  elevacao_lateral_polia: { src: "Standing_Low-Pulley_Deltoid_Raise" },
  elevacao_frontal: { src: "Front_Dumbbell_Raise" },
  crucifixo_inverso: { src: "Reverse_Flyes" },
  voador_inverso: { src: "Reverse_Machine_Flyes" },
  face_pull: { src: "Face_Pull" },
  // Braços
  rosca_direta_halteres: { src: "Dumbbell_Bicep_Curl" },
  rosca_martelo: { src: "Hammer_Curls" },
  rosca_barra: { src: "Barbell_Curl" },
  rosca_elastico: { src: "Standing_Biceps_Cable_Curl", approx: true },
  rosca_concentrada: { src: "Concentration_Curls" },
  rosca_polia: { src: "Standing_Biceps_Cable_Curl" },
  rosca_scott_polia: { src: "Cable_Preacher_Curl" },
  rosca_martelo_corda: { src: "Cable_Hammer_Curls_-_Rope_Attachment" },
  triceps_frances: { src: "Standing_Dumbbell_Triceps_Extension" },
  triceps_polia: { src: "Triceps_Pushdown" },
  triceps_corda: { src: "Triceps_Pushdown_-_Rope_Attachment" },
  triceps_frances_polia: { src: "Triceps_Overhead_Extension_with_Rope" },
  triceps_banco: { src: "Bench_Dips" },
  triceps_elastico: { src: "Triceps_Pushdown", approx: true },
  triceps_testa: { src: "EZ-Bar_Skullcrusher" },
  // Pernas
  agachamento_livre: { src: "Bodyweight_Squat" },
  agachamento_goblet: { src: "Goblet_Squat" },
  agachamento_barra: { src: "Barbell_Squat" },
  agachamento_frontal: { src: "Front_Squat_Clean_Grip" },
  agachamento_smith: { src: "Smith_Machine_Squat" },
  leg_press: { src: "Leg_Press" },
  leg_press_fechado: { src: "Narrow_Stance_Leg_Press" },
  hack: { src: "Hack_Squat" },
  agachamento_sumo: { src: "Plie_Dumbbell_Squat" },
  agachamento_salto: { src: "Freehand_Jump_Squat" },
  agachamento_elastico: { src: "Squats_-_With_Bands" },
  agachamento_caixa: { src: "Chair_Squat" },
  pistol_assistido: { src: "Kettlebell_Pistol_Squat", approx: true },
  afundo: { src: "Bodyweight_Walking_Lunge" },
  afundo_halteres: { src: "Dumbbell_Lunges" },
  bulgaro: { src: "Split_Squats" },
  bulgaro_halteres: { src: "Split_Squat_with_Dumbbells" },
  bulgaro_smith: { src: "Smith_Single-Leg_Split_Squat" },
  subida_banco: { src: "Dumbbell_Step_Ups", approx: true },
  afundo_reverso: { src: "Dumbbell_Rear_Lunge", approx: true },
  terra: { src: "Barbell_Deadlift" },
  stiff_halteres: { src: "Stiff-Legged_Dumbbell_Deadlift" },
  stiff_barra: { src: "Romanian_Deadlift" },
  stiff_smith: { src: "Smith_Machine_Stiff-Legged_Deadlift" },
  stiff_unilateral: { src: "Kettlebell_One-Legged_Deadlift", approx: true },
  kb_swing: { src: "One-Arm_Kettlebell_Swings" },
  hip_thrust: { src: "Barbell_Hip_Thrust" },
  hip_thrust_smith: { src: "Smith_Machine_Hip_Raise" },
  ponte_gluteo: { src: "Butt_Lift_Bridge" },
  ponte_unilateral: { src: "Single_Leg_Glute_Bridge" },
  good_morning_elastico: { src: "Band_Good_Morning" },
  mesa_flexora: { src: "Lying_Leg_Curls" },
  cadeira_flexora: { src: "Seated_Leg_Curl" },
  cadeira_extensora: { src: "Leg_Extensions" },
  cadeira_abdutora: { src: "Thigh_Abductor" },
  abducao_elastico: { src: "Monster_Walk", approx: true },
  coice_polia: { src: "One-Legged_Cable_Kickback" },
  flexora_bola: { src: "Ball_Leg_Curl" },
  nordica: { src: "Natural_Glute_Ham_Raise" },
  panturrilha_pe: { src: "Rocking_Standing_Calf_Raise" },
  panturrilha_unilateral: { src: "Calf_Raise_On_A_Dumbbell" },
  panturrilha_maquina: { src: "Standing_Calf_Raises" },
  panturrilha_leg_press: { src: "Calf_Press_On_The_Leg_Press_Machine" },
  panturrilha_sentado: { src: "Seated_Calf_Raise" },
  // Core
  prancha: { src: "Plank" },
  prancha_lateral: { src: "Side_Bridge" },
  dead_bug: { src: "Dead_Bug" },
  abdominal_supra: { src: "Crunches" },
  abdominal_polia: { src: "Cable_Crunch" },
  abdominal_maquina: { src: "Ab_Crunch_Machine" },
  elevacao_pernas: { src: "Flat_Bench_Lying_Leg_Raise" },
  elevacao_pernas_barra: { src: "Hanging_Leg_Raise" },
  mountain_climber: { src: "Mountain_Climbers" },
  pallof: { src: "Pallof_Press" },
  abdominal_bicicleta: { src: "Air_Bike" },
  roda_abdominal: { src: "Ab_Roller" },
  farmer_walk: { src: "Farmers_Walk" },
  kb_turkish: { src: "Kettlebell_Turkish_Get-Up_Squat_style" },
  // Condicionamento
  polichinelo: { src: "Star_Jump", approx: true },
  corrida_estacionaria: { src: "Fast_Skipping", approx: true },
  corda: { src: "Rope_Jumping" },
  esteira_intervalado: { src: "Running_Treadmill" },
  caminhada_inclinada: { src: "Walking_Treadmill" },
  remo_ergometro: { src: "Rowing_Stationary" },
  bike_ergometrica: { src: "Bicycling_Stationary" },
  eliptico: { src: "Elliptical_Trainer" },
  escada: { src: "Stairmaster" },
  kb_clean_press: { src: "One-Arm_Kettlebell_Clean_and_Jerk", approx: true },
  thruster_halteres: { src: "Kettlebell_Thruster", approx: true },
  patinador: { src: "Lateral_Bound" },
  // Mobilidade
  gato_camelo: { src: "Cat_Stretch" },
  alongamento_posterior: { src: "Hamstring_Stretch" },
};

export function exerciseImages(id: string): { frames: [string, string]; approx: boolean } | null {
  const hit = EXERCISE_IMAGES[id];
  if (!hit) return null;
  const base = `/fit/exercicios/${hit.src}`;
  return { frames: [`${base}/0.webp`, `${base}/1.webp`], approx: !!hit.approx };
}
