import type { Equipment, Limitation, Muscle } from "./types";

/** Movement pattern — the generator fills each session slot by pattern
 * first, then picks the best exercise the user can actually do. */
export type Pattern =
  | "empurrar_h" // supino, flexão
  | "empurrar_v" // desenvolvimento
  | "puxar_h" // remadas
  | "puxar_v" // barra, puxada
  | "agachar"
  | "dobrar_quadril" // terra, stiff, hip thrust
  | "unilateral_perna" // afundo, búlgaro
  | "isolado_braco"
  | "isolado_ombro"
  | "isolado_perna"
  | "core"
  | "condicionamento"
  | "mobilidade";

export type Exercise = {
  id: string;
  name: string;
  muscle: Muscle;
  secondary: Muscle[];
  pattern: Pattern;
  /** Any one inner list satisfies the requirement (all items of it needed).
   * An empty outer list means nothing but the floor. */
  equipment: Equipment[][];
  /** 1 = iniciante, 2 = intermediário, 3 = avançado. */
  difficulty: 1 | 2 | 3;
  compound: boolean;
  /** Skipped entirely when the user reports one of these. */
  avoid: Limitation[];
  /** Reps-based or held/timed (seconds). */
  unit: "reps" | "seg";
  cues: string[];
};

type Def = [
  id: string,
  name: string,
  muscle: Muscle,
  secondary: Muscle[],
  pattern: Pattern,
  equipment: Equipment[][],
  difficulty: 1 | 2 | 3,
  compound: boolean,
  avoid: Limitation[],
  cues: string[],
  unit?: "reps" | "seg",
];

const BW: Equipment[][] = [];
const DB: Equipment[][] = [["halteres"]];
const DB_BENCH: Equipment[][] = [["halteres", "banco"]];
const BB: Equipment[][] = [["barra", "anilhas"]];
const BB_BENCH: Equipment[][] = [["barra", "anilhas", "banco"]];
const GYM: Equipment[][] = [["academia"]];
const KB: Equipment[][] = [["kettlebell"]];
const BAND: Equipment[][] = [["elastico"]];
const PULLUP: Equipment[][] = [["barra_fixa"]];
const PLATES: Equipment[][] = [["anilhas"]];
/** A machine: full gym, or the user marked that specific aparelho. */
const M = (...machines: Equipment[]): Equipment[][] => [["academia"], ...machines.map((m) => [m])];

const DEFS: Def[] = [
  // ---------------- Peito ----------------
  ["flexao", "Flexão de braço", "peito", ["triceps", "ombros", "core"], "empurrar_h", BW, 1, true, ["punho"], ["Corpo em prancha, glúteo contraído", "Cotovelos a ~45° do tronco", "Peito quase encosta no chão"]],
  ["flexao_inclinada", "Flexão inclinada (mãos elevadas)", "peito", ["triceps", "ombros"], "empurrar_h", BW, 1, true, [], ["Mãos num banco, sofá ou parede", "Quanto mais alto, mais fácil", "Desça controlando 2 segundos"]],
  ["flexao_declinada", "Flexão declinada (pés elevados)", "peito", ["ombros", "triceps"], "empurrar_h", BW, 2, true, ["punho", "ombro"], ["Pés elevados, foco na parte alta do peito", "Não deixe o quadril cair"]],
  ["flexao_explosiva", "Flexão explosiva", "peito", ["triceps", "ombros"], "empurrar_h", BW, 3, true, ["punho", "ombro"], ["Desça controlado e suba com máxima velocidade", "Mãos podem sair do chão"]],
  ["flexao_diamante", "Flexão diamante", "triceps", ["peito"], "empurrar_h", BW, 2, true, ["punho"], ["Mãos juntas formando um losango", "Cotovelos rentes ao corpo"]],
  ["supino_halteres", "Supino reto com halteres", "peito", ["triceps", "ombros"], "empurrar_h", [["halteres", "banco"], ["academia"]], 1, true, [], ["Escápulas retraídas no banco", "Desça até alongar o peito", "Suba aproximando os halteres"]],
  ["supino_halteres_chao", "Supino no chão com halteres", "peito", ["triceps"], "empurrar_h", DB, 1, true, [], ["Deitado no chão, cotovelos tocam o solo", "Ótimo para quem não tem banco"]],
  ["supino_inclinado_halteres", "Supino inclinado com halteres", "peito", ["ombros", "triceps"], "empurrar_h", [["halteres", "banco"], ["academia"]], 2, true, [], ["Banco a 30°", "Foco na parte superior do peito"]],
  ["supino_barra", "Supino reto com barra", "peito", ["triceps", "ombros"], "empurrar_h", [...BB_BENCH, ...GYM], 2, true, ["ombro"], ["Pés firmes, arco leve na lombar", "Barra desce na linha do mamilo", "Use sempre alguém para ajudar em cargas altas"]],
  ["supino_maquina", "Supino na máquina", "peito", ["triceps"], "empurrar_h", M("maquinas_peito_ombro"), 1, true, [], ["Ajuste o banco: pegadas na linha do peito", "Controle a volta"]],
  ["crucifixo_halteres", "Crucifixo com halteres", "peito", [], "empurrar_h", [["halteres", "banco"], ["academia"]], 1, false, ["ombro"], ["Cotovelos levemente flexionados", "Abra até sentir alongar, sem dor"]],
  ["crossover", "Crossover na polia", "peito", [], "empurrar_h", M("polia"), 1, false, [], ["Passo à frente, tronco levemente inclinado", "Junte as mãos na frente do peito"]],
  ["crucifixo_elastico", "Crucifixo com elástico", "peito", [], "empurrar_h", BAND, 1, false, [], ["Elástico preso atrás na altura do peito", "Abrace uma árvore imaginária"]],
  ["mergulho_paralelas", "Mergulho nas paralelas", "peito", ["triceps", "ombros"], "empurrar_h", [["paralelas"], ["academia"]], 3, true, ["ombro"], ["Tronco inclinado à frente para peito", "Desça até o ombro na linha do cotovelo"]],
  ["flexao_trx", "Flexão no TRX", "peito", ["core", "triceps"], "empurrar_h", [["trx"]], 2, true, ["ombro"], ["Alças na altura do quadril", "Core bem firme"]],

  // ---------------- Costas ----------------
  ["barra_fixa", "Barra fixa pronada", "costas", ["biceps"], "puxar_v", [...PULLUP, ...GYM], 3, true, ["ombro"], ["Comece com braços estendidos", "Leve o peito em direção à barra", "Desça controlando"]],
  ["barra_supinada", "Barra fixa supinada", "costas", ["biceps"], "puxar_v", [...PULLUP, ...GYM], 2, true, ["ombro"], ["Palmas para você", "Queixo passa a barra"]],
  ["barra_negativa", "Barra fixa negativa", "costas", ["biceps"], "puxar_v", [...PULLUP, ...GYM], 1, true, ["ombro"], ["Suba com ajuda de um apoio", "Desça em 4-5 segundos"]],
  ["barra_elastico", "Barra fixa assistida com elástico", "costas", ["biceps"], "puxar_v", [["barra_fixa", "elastico"]], 1, true, ["ombro"], ["Elástico no joelho ou pé", "Mesma técnica da barra"]],
  ["puxada_frente", "Puxada frontal", "costas", ["biceps"], "puxar_v", M("polia", "maquinas_costas"), 1, true, [], ["Peito aberto, leve inclinação para trás", "Puxe até o alto do peito"]],
  ["puxada_elastico", "Puxada alta com elástico", "costas", ["biceps"], "puxar_v", BAND, 1, true, [], ["Elástico preso no alto da porta", "Cotovelos descem para os bolsos"]],
  ["remada_curvada_barra", "Remada curvada com barra", "costas", ["biceps", "posterior"], "puxar_h", [...BB, ...GYM], 2, true, ["lombar"], ["Quadril para trás, coluna neutra", "Puxe a barra até o umbigo"]],
  ["remada_unilateral", "Remada unilateral com halter", "costas", ["biceps"], "puxar_h", [...DB, ...GYM], 1, true, [], ["Mão e joelho apoiados", "Leve o cotovelo em direção ao quadril"]],
  ["remada_curvada_halteres", "Remada curvada com halteres", "costas", ["biceps"], "puxar_h", [...DB, ...GYM], 2, true, ["lombar"], ["Tronco a ~45°", "Aperte as escápulas no topo"]],
  ["remada_baixa", "Remada baixa na polia", "costas", ["biceps"], "puxar_h", M("polia"), 1, true, [], ["Coluna ereta", "Puxe o triângulo até o abdômen"]],
  ["remada_elastico", "Remada com elástico", "costas", ["biceps"], "puxar_h", BAND, 1, true, [], ["Sentado com pernas estendidas", "Cotovelos rentes ao corpo"]],
  ["remada_invertida", "Remada invertida", "costas", ["biceps", "core"], "puxar_h", [["trx"], ["barra_fixa"], ["academia"]], 1, true, [], ["Corpo reto como prancha", "Peito vai até as mãos", "Quanto mais em pé, mais fácil"]],
  ["remada_toalha", "Remada isométrica com toalha na porta", "costas", ["biceps"], "puxar_h", BW, 1, true, [], ["Toalha presa na maçaneta", "Incline o corpo para trás e puxe"]],
  ["superman", "Superman", "costas", ["gluteos"], "puxar_h", BW, 1, false, [], ["Deitado de bruços, eleve braços e pernas", "Segure 2 segundos no alto"]],
  ["pulldown_braco_estendido", "Pulldown com braços estendidos", "costas", [], "puxar_v", [...M("polia"), ...BAND], 1, false, [], ["Braços quase retos", "Leve as mãos até as coxas"]],
  ["kb_remada", "Remada com kettlebell", "costas", ["biceps"], "puxar_h", KB, 1, true, [], ["Mesma técnica da remada unilateral"]],

  // ---------------- Ombros ----------------
  ["desenvolvimento_halteres", "Desenvolvimento com halteres", "ombros", ["triceps"], "empurrar_v", [...DB, ...GYM], 1, true, ["ombro", "cervical"], ["Sentado ou em pé, abdômen firme", "Empurre até quase estender os braços"]],
  ["desenvolvimento_barra", "Desenvolvimento militar com barra", "ombros", ["triceps", "core"], "empurrar_v", [...BB, ...GYM], 2, true, ["ombro", "lombar", "cervical"], ["Em pé, glúteo contraído", "Cabeça passa para frente quando a barra sobe"]],
  ["desenvolvimento_maquina", "Desenvolvimento na máquina", "ombros", ["triceps"], "empurrar_v", M("maquinas_peito_ombro"), 1, true, ["cervical"], ["Pegadas na linha do queixo"]],
  ["pike_pushup", "Flexão pike", "ombros", ["triceps"], "empurrar_v", BW, 2, true, ["punho", "ombro", "hipertensao"], ["Quadril alto em V invertido", "Cabeça desce à frente das mãos"]],
  ["desenvolvimento_elastico", "Desenvolvimento com elástico", "ombros", ["triceps"], "empurrar_v", BAND, 1, true, [], ["Pise no elástico", "Empurre para cima sem arquear"]],
  ["kb_press", "Press com kettlebell", "ombros", ["triceps", "core"], "empurrar_v", KB, 2, true, ["ombro"], ["Kettlebell apoiado no antebraço", "Suba girando levemente"]],
  ["elevacao_lateral", "Elevação lateral", "ombros", [], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Cotovelos levemente flexionados", "Suba até a linha do ombro"]],
  ["elevacao_lateral_elastico", "Elevação lateral com elástico", "ombros", [], "isolado_ombro", BAND, 1, false, [], ["Pise no elástico, suba até a linha do ombro"]],
  ["elevacao_frontal", "Elevação frontal", "ombros", [], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Braços retos até a altura dos olhos"]],
  ["crucifixo_inverso", "Crucifixo inverso", "ombros", ["costas"], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Tronco inclinado", "Abra os braços apertando as escápulas"]],
  ["face_pull", "Face pull", "ombros", ["costas"], "isolado_ombro", [...M("polia"), ...BAND], 1, false, [], ["Puxe a corda em direção ao rosto", "Cotovelos altos, gire para fora"]],
  ["y_raise", "Y-raise deitado", "ombros", ["costas"], "isolado_ombro", BW, 1, false, [], ["De bruços, braços em Y", "Polegar para cima"]],

  // ---------------- Braços ----------------
  ["rosca_direta_halteres", "Rosca direta com halteres", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Cotovelos parados ao lado do corpo", "Gire o punho ao subir"]],
  ["rosca_martelo", "Rosca martelo", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Pegada neutra", "Sem balançar o tronco"]],
  ["rosca_barra", "Rosca direta com barra", "biceps", [], "isolado_braco", [...BB, ...GYM], 1, false, ["punho"], ["Pegada na largura dos ombros"]],
  ["rosca_elastico", "Rosca com elástico", "biceps", [], "isolado_braco", BAND, 1, false, [], ["Pise no elástico", "Controle a descida"]],
  ["rosca_concentrada", "Rosca concentrada", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Cotovelo apoiado na coxa"]],
  ["rosca_toalha", "Rosca isométrica com toalha", "biceps", [], "isolado_braco", BW, 1, false, [], ["Pise na toalha e puxe com força", "Segure a contração"], "seg"],
  ["triceps_frances", "Tríceps francês com halter", "triceps", [], "isolado_braco", [...DB, ...GYM], 1, false, ["ombro"], ["Cotovelos apontando para cima", "Desça atrás da cabeça"]],
  ["triceps_polia", "Tríceps na polia", "triceps", [], "isolado_braco", M("polia"), 1, false, [], ["Cotovelos colados", "Estenda totalmente"]],
  ["triceps_banco", "Mergulho no banco", "triceps", ["peito"], "isolado_braco", BW, 1, false, ["ombro", "punho"], ["Mãos no banco/cadeira", "Desça até 90° no cotovelo"]],
  ["triceps_elastico", "Tríceps com elástico", "triceps", [], "isolado_braco", BAND, 1, false, [], ["Elástico preso no alto", "Estenda os braços para baixo"]],
  ["triceps_testa", "Tríceps testa", "triceps", [], "isolado_braco", [...DB_BENCH, ...BB_BENCH, ...GYM], 2, false, ["punho"], ["Desça até próximo da testa", "Cotovelos fixos"]],

  // ---------------- Pernas: agachar ----------------
  ["agachamento_livre", "Agachamento livre (peso corporal)", "quadriceps", ["gluteos", "core"], "agachar", BW, 1, true, [], ["Pés na largura do ombro", "Quadril para trás e para baixo", "Joelhos acompanham a ponta dos pés"]],
  ["agachamento_goblet", "Agachamento goblet", "quadriceps", ["gluteos", "core"], "agachar", [...DB, ...KB, ...GYM], 1, true, [], ["Halter/kettlebell junto ao peito", "Cotovelos entre os joelhos no fundo"]],
  ["agachamento_barra", "Agachamento com barra", "quadriceps", ["gluteos", "posterior", "core"], "agachar", [...BB, ...GYM], 2, true, ["lombar", "joelho"], ["Barra no trapézio", "Respire e trave o abdômen antes de descer", "Profundidade até coxa paralela ou abaixo"]],
  ["agachamento_frontal", "Agachamento frontal", "quadriceps", ["core"], "agachar", [...BB, ...GYM], 3, true, ["punho", "lombar"], ["Barra apoiada nos ombros", "Tronco bem ereto"]],
  ["leg_press", "Leg press 45°", "quadriceps", ["gluteos"], "agachar", M("leg_press"), 1, true, [], ["Lombar sempre apoiada", "Não trave os joelhos no topo"]],
  ["hack", "Agachamento hack", "quadriceps", ["gluteos"], "agachar", M("leg_press"), 2, true, ["joelho"], ["Costas apoiadas", "Desça controlado"]],
  ["agachamento_sumo", "Agachamento sumô", "gluteos", ["quadriceps", "posterior"], "agachar", [...DB, ...KB, ...GYM, ...BW], 1, true, [], ["Pés afastados e apontados para fora", "Tronco ereto"]],
  ["agachamento_isometrico", "Agachamento isométrico na parede", "quadriceps", [], "agachar", BW, 1, false, [], ["Costas na parede, joelhos a 90°", "Segure o tempo"], "seg"],
  ["agachamento_salto", "Agachamento com salto", "quadriceps", ["gluteos", "cardio"], "agachar", BW, 2, true, ["joelho", "gestante"], ["Aterrisse macio", "Emende direto na próxima"]],
  ["agachamento_elastico", "Agachamento com elástico", "quadriceps", ["gluteos"], "agachar", BAND, 1, true, [], ["Mini band acima dos joelhos", "Empurre os joelhos para fora"]],
  ["agachamento_caixa", "Agachamento no banco (box squat)", "quadriceps", ["gluteos"], "agachar", BW, 1, true, [], ["Sente de leve no banco e levante", "Ótimo para aprender o movimento"]],
  ["pistol_assistido", "Pistol squat assistido", "quadriceps", ["gluteos", "core"], "unilateral_perna", BW, 3, true, ["joelho"], ["Segure num apoio", "Desça em uma perna só"]],

  // ---------------- Pernas: unilateral ----------------
  ["afundo", "Afundo alternado", "quadriceps", ["gluteos"], "unilateral_perna", BW, 1, true, ["joelho"], ["Passo largo à frente", "Joelho de trás quase toca o chão"]],
  ["afundo_halteres", "Afundo com halteres", "quadriceps", ["gluteos"], "unilateral_perna", [...DB, ...GYM], 2, true, ["joelho"], ["Halteres ao lado do corpo", "Tronco ereto"]],
  ["bulgaro", "Agachamento búlgaro", "quadriceps", ["gluteos"], "unilateral_perna", BW, 2, true, ["joelho"], ["Pé de trás apoiado no banco/sofá", "Desça reto"]],
  ["bulgaro_halteres", "Búlgaro com halteres", "quadriceps", ["gluteos"], "unilateral_perna", [...DB, ...GYM], 3, true, ["joelho"], ["Mesma técnica, com carga"]],
  ["subida_banco", "Subida no banco (step-up)", "gluteos", ["quadriceps"], "unilateral_perna", BW, 1, true, [], ["Suba empurrando o calcanhar", "Desça controlado"]],
  ["afundo_reverso", "Afundo reverso", "gluteos", ["quadriceps"], "unilateral_perna", BW, 1, true, [], ["Passo para trás — mais amigável ao joelho"]],

  // ---------------- Pernas: quadril ----------------
  ["terra", "Levantamento terra", "posterior", ["gluteos", "costas", "core"], "dobrar_quadril", [...BB, ...GYM], 3, true, ["lombar", "hipertensao"], ["Barra rente à canela", "Coluna neutra do início ao fim", "Empurre o chão com os pés"]],
  ["stiff_halteres", "Stiff com halteres", "posterior", ["gluteos"], "dobrar_quadril", [...DB, ...GYM], 1, true, ["lombar"], ["Joelhos semiflexionados", "Leve o quadril para trás até alongar a posterior"]],
  ["stiff_barra", "Stiff com barra", "posterior", ["gluteos"], "dobrar_quadril", [...BB, ...GYM], 2, true, ["lombar"], ["Barra desliza pelas coxas"]],
  ["stiff_unilateral", "Stiff unilateral", "posterior", ["gluteos", "core"], "dobrar_quadril", BW, 2, true, [], ["Uma perna vai para trás como gangorra", "Quadril alinhado"]],
  ["kb_swing", "Kettlebell swing", "gluteos", ["posterior", "core", "cardio"], "dobrar_quadril", KB, 2, true, ["lombar"], ["Movimento é de quadril, não de braço", "Contraia o glúteo no topo"]],
  ["hip_thrust", "Hip thrust", "gluteos", ["posterior"], "dobrar_quadril", [["banco"], ["barra", "anilhas", "banco"], ["academia"]], 1, true, [], ["Escápulas no banco", "Suba até alinhar tronco e coxa", "Segure 1 segundo no topo"]],
  ["ponte_gluteo", "Ponte de glúteo", "gluteos", ["posterior"], "dobrar_quadril", BW, 1, false, [], ["Deitado, pés próximos ao quadril", "Suba contraindo o glúteo"]],
  ["ponte_unilateral", "Ponte de glúteo unilateral", "gluteos", ["posterior"], "dobrar_quadril", BW, 2, false, [], ["Uma perna estendida no ar"]],
  ["good_morning_elastico", "Good morning com elástico", "posterior", ["gluteos"], "dobrar_quadril", BAND, 1, true, [], ["Elástico sob os pés e atrás do pescoço", "Incline o tronco com coluna neutra"]],
  ["mesa_flexora", "Mesa flexora", "posterior", [], "isolado_perna", M("extensora_flexora"), 1, false, [], ["Quadril colado no banco", "Controle a volta"]],
  ["cadeira_extensora", "Cadeira extensora", "quadriceps", [], "isolado_perna", M("extensora_flexora"), 1, false, ["joelho"], ["Segure 1 segundo em cima"]],
  ["cadeira_abdutora", "Cadeira abdutora", "gluteos", [], "isolado_perna", M("abdutora"), 1, false, [], ["Tronco levemente à frente para mais glúteo"]],
  ["abducao_elastico", "Abdução com mini band", "gluteos", [], "isolado_perna", BAND, 1, false, [], ["Deitado de lado ou em pé", "Movimento controlado"]],
  ["flexora_bola", "Flexão de joelho na bola suíça", "posterior", ["gluteos", "core"], "isolado_perna", [["bola_suica"]], 2, false, [], ["Quadril elevado", "Puxe a bola com os calcanhares"]],
  ["nordica", "Flexão nórdica", "posterior", [], "isolado_perna", BW, 3, false, ["joelho"], ["Pés presos", "Desça o mais devagar possível"]],
  ["panturrilha_pe", "Elevação de panturrilha em pé", "panturrilha", [], "isolado_perna", BW, 1, false, [], ["Use um degrau para amplitude", "Pausa em cima e embaixo"]],
  ["panturrilha_unilateral", "Panturrilha unilateral com halter", "panturrilha", [], "isolado_perna", [...DB, ...GYM], 2, false, [], ["Segure num apoio", "Amplitude total"]],
  ["panturrilha_maquina", "Panturrilha na máquina", "panturrilha", [], "isolado_perna", M("panturrilha_maquina"), 1, false, [], ["Joelhos estendidos"]],

  // ---------------- Core ----------------
  ["prancha", "Prancha", "core", [], "core", BW, 1, false, ["gestante"], ["Cotovelos sob os ombros", "Glúteo e abdômen contraídos", "Não deixe o quadril cair"], "seg"],
  ["prancha_lateral", "Prancha lateral", "core", [], "core", BW, 1, false, ["ombro"], ["Corpo alinhado de lado", "Quadril alto"], "seg"],
  ["dead_bug", "Dead bug", "core", [], "core", BW, 1, false, [], ["Lombar colada no chão", "Estenda braço e perna opostos"]],
  ["bird_dog", "Bird dog", "core", ["costas"], "core", BW, 1, false, [], ["Quatro apoios", "Estenda braço e perna opostos sem girar o quadril"]],
  ["abdominal_supra", "Abdominal supra", "core", [], "core", BW, 1, false, ["cervical", "gestante"], ["Mãos sem puxar o pescoço", "Suba só as escápulas"]],
  ["elevacao_pernas", "Elevação de pernas", "core", [], "core", BW, 2, false, ["lombar", "gestante"], ["Lombar colada no chão", "Desça devagar"]],
  ["elevacao_pernas_barra", "Elevação de pernas na barra", "core", [], "core", [...PULLUP, ...GYM], 3, false, ["ombro"], ["Sem balanço", "Suba os joelhos ao peito ou pernas estendidas"]],
  ["mountain_climber", "Mountain climber", "core", ["cardio"], "core", BW, 1, false, ["punho"], ["Posição de prancha alta", "Joelhos ao peito alternando rápido"]],
  ["pallof", "Pallof press", "core", [], "core", [...BAND, ...M("polia")], 1, false, [], ["De lado para a âncora", "Empurre à frente sem deixar girar"]],
  ["abdominal_bicicleta", "Abdominal bicicleta", "core", [], "core", BW, 1, false, ["cervical", "gestante"], ["Cotovelo vai ao joelho oposto", "Ritmo controlado"]],
  ["hollow_hold", "Hollow hold", "core", [], "core", BW, 2, false, ["lombar", "gestante"], ["Lombar no chão, pernas e braços estendidos", "Segure a posição de canoa"], "seg"],
  ["roda_abdominal", "Roda abdominal", "core", ["ombros"], "core", GYM, 3, false, ["lombar", "gestante"], ["De joelhos", "Estenda só até onde a lombar aguenta"]],
  ["farmer_walk", "Caminhada do fazendeiro", "core", ["costas", "biceps"], "core", [...DB, ...KB, ...GYM], 1, true, [], ["Carga pesada nas mãos", "Caminhe ereto por tempo ou distância"], "seg"],
  ["kb_turkish", "Turkish get-up", "core", ["ombros", "gluteos"], "core", KB, 3, true, ["ombro"], ["Olhos no kettlebell o tempo todo", "Movimento lento e fragmentado"]],

  // ---------------- Condicionamento ----------------
  ["polichinelo", "Polichinelo", "cardio", [], "condicionamento", BW, 1, false, ["gestante"], ["Ritmo constante", "Aterrisse na ponta dos pés"], "seg"],
  ["burpee", "Burpee", "cardio", ["peito", "quadriceps", "core"], "condicionamento", BW, 2, true, ["joelho", "punho", "hipertensao", "gestante"], ["Agache, prancha, flexão, salto", "Mantenha um ritmo que dê para sustentar"]],
  ["corrida_estacionaria", "Corrida estacionária (skipping)", "cardio", [], "condicionamento", BW, 1, false, ["gestante"], ["Joelhos altos", "Braços acompanham"], "seg"],
  ["corda", "Pular corda", "cardio", ["panturrilha"], "condicionamento", [["corda"]], 1, false, ["joelho", "gestante"], ["Saltos baixos", "Giro no punho"], "seg"],
  ["esteira_intervalado", "Intervalado na esteira/bike", "cardio", [], "condicionamento", [["cardio_maquina"], ["academia"]], 1, false, [], ["30s forte / 60s leve", "Ajuste a intensidade à sua respiração"], "seg"],
  ["remo_ergometro", "Remo ergômetro", "cardio", ["costas"], "condicionamento", GYM, 1, true, ["lombar"], ["Pernas, tronco, braços — e volta na ordem inversa"], "seg"],
  ["shadow_boxing", "Shadow boxing", "cardio", ["ombros", "core"], "condicionamento", BW, 1, false, [], ["Socos rápidos com giro do quadril", "Mantenha a guarda"], "seg"],
  ["kb_clean_press", "Kettlebell clean & press", "cardio", ["ombros", "gluteos"], "condicionamento", KB, 3, true, ["ombro", "lombar"], ["Clean com o quadril, press em seguida"]],
  ["thruster_halteres", "Thruster com halteres", "cardio", ["quadriceps", "ombros"], "condicionamento", [...DB, ...GYM], 2, true, ["ombro"], ["Agachamento + desenvolvimento num só movimento"]],
  ["patinador", "Salto do patinador", "cardio", ["gluteos"], "condicionamento", BW, 2, false, ["joelho", "gestante"], ["Salte de lado em uma perna", "Equilíbrio na aterrissagem"], "seg"],
  ["caminhada_inclinada", "Caminhada inclinada", "cardio", ["gluteos", "panturrilha"], "condicionamento", [["cardio_maquina"], ["academia"]], 1, false, [], ["Inclinação 8-12%", "Não segure no apoio"], "seg"],

  // ---------------- Aparelhos ----------------
  ["peck_deck", "Voador (peck deck)", "peito", [], "empurrar_h", M("maquinas_peito_ombro"), 1, false, [], ["Cotovelos na altura dos ombros", "Feche os braços apertando o peito", "Volte devagar até sentir alongar"]],
  ["supino_inclinado_maquina", "Supino inclinado na máquina", "peito", ["ombros", "triceps"], "empurrar_h", M("maquinas_peito_ombro"), 1, true, [], ["Pegadas na linha da parte alta do peito", "Empurre sem tirar as costas do encosto"]],
  ["crossover_baixo", "Crossover polia baixa", "peito", ["ombros"], "empurrar_h", M("polia"), 1, false, [], ["Polias embaixo, mãos sobem até a altura do queixo", "Foco na parte superior do peito"]],
  ["supino_smith", "Supino reto no Smith", "peito", ["triceps", "ombros"], "empurrar_h", M("smith"), 1, true, ["ombro"], ["Banco centralizado sob a barra", "Barra desce na linha do mamilo", "Trave de segurança ajustada"]],
  ["supino_inclinado_smith", "Supino inclinado no Smith", "peito", ["ombros", "triceps"], "empurrar_h", M("smith"), 2, true, ["ombro"], ["Banco a 30°", "Barra desce na parte alta do peito"]],
  ["puxada_supinada", "Puxada supinada na polia", "costas", ["biceps"], "puxar_v", M("polia", "maquinas_costas"), 1, true, [], ["Palmas para você, pegada na largura dos ombros", "Puxe até o queixo, cotovelos para baixo"]],
  ["puxada_triangulo", "Puxada com triângulo", "costas", ["biceps"], "puxar_v", M("polia", "maquinas_costas"), 1, true, [], ["Pegada neutra fechada", "Leve o triângulo até o alto do peito"]],
  ["remada_articulada", "Remada articulada", "costas", ["biceps"], "puxar_h", M("maquinas_costas"), 1, true, [], ["Peito apoiado no encosto", "Puxe levando os cotovelos para trás", "Aperte as escápulas"]],
  ["puxada_articulada", "Puxada alta articulada", "costas", ["biceps"], "puxar_v", M("maquinas_costas"), 1, true, [], ["Ajuste o banco para as coxas ficarem presas", "Puxe até a linha do peito"]],
  ["remada_unilateral_polia", "Remada unilateral na polia", "costas", ["biceps"], "puxar_h", M("polia"), 1, true, [], ["Sentado, um braço de cada vez", "Gire levemente o tronco no alongamento"]],
  ["remada_smith", "Remada curvada no Smith", "costas", ["biceps"], "puxar_h", M("smith"), 2, true, ["lombar"], ["Tronco inclinado a ~45°", "Barra sobe até o umbigo"]],
  ["voador_inverso", "Voador inverso (crucifixo inverso na máquina)", "ombros", ["costas"], "isolado_ombro", M("maquinas_peito_ombro"), 1, false, [], ["Peito apoiado no encosto", "Abra os braços até a linha do corpo"]],
  ["elevacao_lateral_polia", "Elevação lateral na polia", "ombros", [], "isolado_ombro", M("polia"), 1, false, [], ["Polia baixa, cabo passando pela frente do corpo", "Suba até a linha do ombro"]],
  ["desenvolvimento_smith", "Desenvolvimento no Smith", "ombros", ["triceps"], "empurrar_v", M("smith"), 1, true, ["ombro", "cervical"], ["Sentado, barra desce à frente do rosto", "Empurre até quase estender"]],
  ["rosca_polia", "Rosca direta na polia", "biceps", [], "isolado_braco", M("polia"), 1, false, [], ["Cotovelos fixos ao lado do corpo", "Tensão constante na subida e descida"]],
  ["rosca_scott_polia", "Rosca Scott na polia", "biceps", [], "isolado_braco", M("polia"), 1, false, [], ["Braços apoiados no banco Scott", "Não estenda totalmente o cotovelo no fim"]],
  ["rosca_martelo_corda", "Rosca martelo na corda", "biceps", [], "isolado_braco", M("polia"), 1, false, [], ["Corda na polia baixa, pegada neutra", "Cotovelos parados"]],
  ["triceps_corda", "Tríceps na corda", "triceps", [], "isolado_braco", M("polia"), 1, false, [], ["Cotovelos colados no corpo", "Abra a corda no final do movimento"]],
  ["triceps_frances_polia", "Tríceps francês na polia", "triceps", [], "isolado_braco", M("polia"), 1, false, ["ombro"], ["De costas para a polia, corda atrás da cabeça", "Estenda os braços à frente"]],
  ["agachamento_smith", "Agachamento no Smith", "quadriceps", ["gluteos"], "agachar", M("smith"), 1, true, [], ["Pés um pouco à frente da barra", "Desça até a coxa paralela", "Trave de segurança ajustada"]],
  ["leg_press_fechado", "Leg press com pés juntos", "quadriceps", [], "agachar", M("leg_press"), 1, true, ["joelho"], ["Pés mais baixos e próximos na plataforma", "Foco no quadríceps"]],
  ["bulgaro_smith", "Agachamento búlgaro no Smith", "quadriceps", ["gluteos"], "unilateral_perna", M("smith"), 2, true, ["joelho"], ["Pé de trás apoiado no banco", "Barra guia o movimento: foque na perna da frente"]],
  ["stiff_smith", "Stiff no Smith", "posterior", ["gluteos"], "dobrar_quadril", M("smith"), 1, true, ["lombar"], ["Joelhos semiflexionados", "Barra desliza pelas coxas"]],
  ["hip_thrust_smith", "Elevação de quadril no Smith", "gluteos", ["posterior"], "dobrar_quadril", M("smith"), 1, true, [], ["Deitado no chão, barra sobre o quadril com proteção", "Suba contraindo o glúteo"]],
  ["cadeira_flexora", "Cadeira flexora (sentado)", "posterior", [], "isolado_perna", M("extensora_flexora"), 1, false, [], ["Joelho alinhado ao eixo da máquina", "Puxe até o máximo e volte devagar"]],
  ["coice_polia", "Glúteo na polia (coice)", "gluteos", ["posterior"], "isolado_perna", M("polia"), 1, false, [], ["Tornozeleira na polia baixa", "Leve a perna para trás sem arquear a lombar"]],
  ["panturrilha_leg_press", "Panturrilha no leg press", "panturrilha", [], "isolado_perna", M("leg_press"), 1, false, [], ["Só a ponta dos pés na plataforma", "Amplitude total, sem travar os joelhos"]],
  ["panturrilha_sentado", "Panturrilha sentado (máquina)", "panturrilha", [], "isolado_perna", M("panturrilha_maquina"), 1, false, [], ["Joelhos a 90°", "Pausa de 1 segundo em cima"]],
  ["abdominal_polia", "Abdominal na polia (crunch ajoelhado)", "core", [], "core", M("polia"), 1, false, ["cervical"], ["Ajoelhado, corda junto à cabeça", "Enrole o tronco levando os cotovelos aos joelhos"]],
  ["abdominal_maquina", "Abdominal na máquina", "core", [], "core", GYM, 1, false, ["cervical", "gestante"], ["Ajuste a carga leve", "Movimento curto e controlado"]],
  ["hiperextensao", "Extensão lombar no banco romano", "costas", ["gluteos", "posterior"], "dobrar_quadril", GYM, 1, false, [], ["Quadril apoiado na almofada", "Suba só até alinhar o corpo, sem hiperestender"]],
  ["bike_ergometrica", "Bike ergométrica", "cardio", ["quadriceps"], "condicionamento", [["cardio_maquina"], ["academia"]], 1, false, [], ["Banco na altura do quadril", "Cadência constante"], "seg"],
  ["eliptico", "Elíptico", "cardio", [], "condicionamento", [["cardio_maquina"], ["academia"]], 1, false, [], ["Postura ereta", "Use braços e pernas"], "seg"],
  ["escada", "Escada / simulador de escada", "cardio", ["gluteos", "panturrilha"], "condicionamento", GYM, 2, false, ["joelho"], ["Não se apoie no corrimão", "Passos completos"], "seg"],

  // ---------------- Mais opções ----------------
  ["supino_inclinado_barra", "Supino inclinado com barra", "peito", ["ombros", "triceps"], "empurrar_h", [...BB_BENCH, ...GYM], 2, true, ["ombro"], ["Banco a 30°", "Barra desce na parte alta do peito"]],
  ["supino_declinado_halteres", "Supino declinado com halteres", "peito", ["triceps"], "empurrar_h", [...DB_BENCH, ...GYM], 2, true, [], ["Pés presos no banco declinado", "Desça até alongar a parte baixa do peito"]],
  ["supino_neutro_halteres", "Supino com halteres pegada neutra", "peito", ["triceps"], "empurrar_h", [...DB_BENCH, ...GYM], 1, true, [], ["Palmas viradas uma para a outra", "Mais confortável para o ombro"]],
  ["supino_unilateral_halter", "Supino unilateral com halter", "peito", ["triceps", "core"], "empurrar_h", [...DB_BENCH, ...GYM], 2, true, [], ["Um braço de cada vez", "Abdômen firme para o corpo não girar"]],
  ["crucifixo_inclinado", "Crucifixo inclinado com halteres", "peito", ["ombros"], "empurrar_h", [...DB_BENCH, ...GYM], 1, false, ["ombro"], ["Banco a 30°", "Abra até sentir alongar a parte alta do peito"]],
  ["crucifixo_polia_banco", "Crucifixo na polia deitado", "peito", [], "empurrar_h", M("polia"), 2, false, [], ["Banco entre as duas polias baixas", "Feche os braços em arco sobre o peito"]],
  ["crossover_unilateral", "Crossover unilateral", "peito", [], "empurrar_h", M("polia"), 1, false, [], ["Um braço de cada vez", "Leve a mão até a linha do meio do corpo"]],
  ["supino_polia_pe", "Supino em pé na polia", "peito", ["triceps", "core"], "empurrar_h", M("polia"), 1, true, [], ["De costas para as polias, passo à frente", "Empurre à frente juntando as mãos"]],
  ["flexao_aberta", "Flexão com mãos afastadas", "peito", ["ombros"], "empurrar_h", BW, 1, true, ["punho"], ["Mãos bem mais abertas que os ombros", "Foco maior no peito"]],
  ["flexao_prancha_lateral", "Flexão com prancha lateral", "peito", ["core", "ombros"], "empurrar_h", BW, 2, true, ["punho", "ombro"], ["Faça a flexão e gire para a prancha lateral", "Alterne os lados"]],
  ["supino_declinado_maquina", "Supino declinado na máquina", "peito", ["triceps"], "empurrar_h", M("maquinas_peito_ombro"), 1, true, [], ["Costas apoiadas", "Empurre para baixo e à frente"]],
  ["svend_press", "Svend press com anilha", "peito", ["ombros"], "empurrar_h", [...PLATES, ...GYM], 1, false, [], ["Aperte a anilha entre as mãos", "Empurre à frente sem deixar de apertar"]],
  ["pullover_halter", "Pullover com halter", "costas", ["peito"], "puxar_v", [...DB_BENCH, ...GYM], 2, false, ["ombro"], ["Deitado, halter acima do peito", "Leve para trás da cabeça com braços quase retos e volte"]],
  ["remada_cavalinho", "Remada cavalinho", "costas", ["biceps"], "puxar_h", [...BB, ...GYM], 2, true, ["lombar"], ["Tronco inclinado, coluna neutra", "Puxe o pegador até o peito"]],
  ["remada_halteres_neutra", "Remada curvada com halteres pegada neutra", "costas", ["biceps"], "puxar_h", [...DB, ...GYM], 2, true, ["lombar"], ["Palmas viradas para o corpo", "Cotovelos rentes ao tronco"]],
  ["remada_apoio_peito", "Remada no banco inclinado (apoio no peito)", "costas", ["biceps"], "puxar_h", [...DB_BENCH, ...GYM], 1, true, [], ["Peito apoiado no banco a 45°", "Poupa a lombar"]],
  ["remada_supinada_barra", "Remada curvada supinada", "costas", ["biceps"], "puxar_h", [...BB, ...GYM], 2, true, ["lombar"], ["Palmas para cima", "Puxe a barra até o umbigo"]],
  ["remada_trx", "Remada no TRX", "costas", ["biceps", "core"], "puxar_h", [["trx"]], 1, true, [], ["Corpo reto, calcanhares no chão", "Quanto mais em pé, mais fácil"]],
  ["kb_remada_alternada", "Remada alternada com kettlebells", "costas", ["biceps", "core"], "puxar_h", KB, 2, true, ["lombar"], ["Tronco inclinado", "Alterne os braços sem girar o tronco"]],
  ["remada_renegada", "Remada renegada", "costas", ["core", "peito"], "puxar_h", [["kettlebell"], ["halteres"], ["academia"]], 3, true, ["punho", "lombar"], ["Prancha alta segurando os pesos", "Reme um braço de cada vez sem girar o quadril"]],
  ["puxada_fechada", "Puxada frontal pegada fechada", "costas", ["biceps"], "puxar_v", M("polia", "maquinas_costas"), 1, true, [], ["Mãos próximas", "Leve a barra até o peito"]],
  ["puxada_unilateral", "Puxada unilateral na polia", "costas", ["biceps"], "puxar_v", M("polia"), 1, true, [], ["Um braço de cada vez", "Cotovelo desce em direção ao quadril"]],
  ["remada_alta_ajoelhado", "Remada alta ajoelhado na polia", "costas", ["biceps"], "puxar_v", M("polia"), 1, true, [], ["Ajoelhado de frente para a polia alta", "Puxe até o peito abrindo os cotovelos"]],
  ["barra_fixa_neutra", "Barra fixa pegada neutra", "costas", ["biceps"], "puxar_v", [...PULLUP, ...GYM], 3, true, ["ombro"], ["Pegador em V ou barra paralela", "Peito em direção à barra"]],
  ["pulldown_corda", "Pulldown na corda", "costas", [], "puxar_v", M("polia"), 1, false, [], ["Braços quase estendidos", "Leve a corda até as coxas"]],
  ["extensao_lombar_solo", "Extensão lombar no solo", "costas", ["gluteos"], "dobrar_quadril", BW, 1, false, [], ["De bruços, mãos na nuca", "Eleve o tronco sem exagerar"]],
  ["encolhimento_halteres", "Encolhimento com halteres", "costas", ["ombros"], "isolado_ombro", [...DB, ...GYM], 1, false, ["cervical"], ["Suba os ombros em direção às orelhas", "Segure 1 segundo em cima"]],
  ["encolhimento_barra", "Encolhimento com barra", "costas", ["ombros"], "isolado_ombro", [...BB, ...GYM], 1, false, ["cervical"], ["Barra à frente do corpo", "Sem girar os ombros"]],
  ["desenvolvimento_arnold", "Desenvolvimento Arnold", "ombros", ["triceps"], "empurrar_v", [...DB, ...GYM], 2, true, ["ombro"], ["Comece com palmas para você", "Gire as mãos enquanto empurra para cima"]],
  ["desenvolvimento_unilateral", "Desenvolvimento unilateral com halter", "ombros", ["triceps", "core"], "empurrar_v", [...DB, ...GYM], 2, true, ["ombro"], ["Um braço de cada vez", "Tronco firme, sem inclinar"]],
  ["desenvolvimento_barra_sentado", "Desenvolvimento sentado com barra", "ombros", ["triceps"], "empurrar_v", [...BB_BENCH, ...GYM], 2, true, ["ombro", "cervical"], ["Sentado com encosto", "Barra desce à frente até o queixo"]],
  ["desenvolvimento_polia", "Desenvolvimento na polia", "ombros", ["triceps"], "empurrar_v", M("polia"), 1, true, ["ombro"], ["Sentado entre as polias", "Empurre para cima unindo as mãos"]],
  ["desenvolvimento_articulado", "Desenvolvimento articulado", "ombros", ["triceps"], "empurrar_v", M("maquinas_peito_ombro"), 1, true, ["cervical"], ["Ajuste o banco: pegadas na altura dos ombros", "Empurre sem arquear"]],
  ["kb_arnold", "Desenvolvimento Arnold com kettlebell", "ombros", ["triceps"], "empurrar_v", KB, 2, true, ["ombro"], ["Kettlebell apoiado no antebraço", "Gire enquanto sobe"]],
  ["kb_push_press", "Push press com kettlebells", "ombros", ["triceps", "quadriceps"], "empurrar_v", KB, 2, true, ["ombro", "lombar"], ["Flexione levemente os joelhos", "Use o impulso das pernas para empurrar"]],
  ["elevacao_lateral_inclinada", "Elevação lateral unilateral inclinada", "ombros", [], "isolado_ombro", [...DB_BENCH, ...GYM], 1, false, [], ["Deitado de lado no banco inclinado", "Suba o braço até a linha do corpo"]],
  ["elevacao_frontal_anilha", "Elevação frontal com anilha", "ombros", [], "isolado_ombro", [...PLATES, ...GYM], 1, false, [], ["Segure a anilha nas laterais", "Suba até a altura dos olhos"]],
  ["elevacao_frontal_polia", "Elevação frontal na polia", "ombros", [], "isolado_ombro", M("polia"), 1, false, [], ["De costas para a polia baixa", "Braço quase estendido"]],
  ["crucifixo_inverso_polia", "Crucifixo inverso na polia", "ombros", ["costas"], "isolado_ombro", M("polia"), 1, false, [], ["Cabos cruzados na altura dos ombros", "Abra os braços para trás"]],
  ["crucifixo_inverso_elastico", "Crucifixo inverso com elástico", "ombros", ["costas"], "isolado_ombro", BAND, 1, false, [], ["Elástico preso à frente", "Abra os braços apertando as escápulas"]],
  ["pull_apart", "Abertura com elástico (pull apart)", "ombros", ["costas"], "isolado_ombro", BAND, 1, false, [], ["Braços estendidos à frente", "Abra o elástico até o peito"]],
  ["rotacao_externa", "Rotação externa com halter", "ombros", [], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Deitado de lado, cotovelo colado", "Gire o antebraço para cima devagar"]],
  ["rotacao_externa_elastico", "Rotação externa com elástico", "ombros", [], "isolado_ombro", BAND, 1, false, [], ["Cotovelo colado ao corpo a 90°", "Gire para fora sem mexer o cotovelo"]],
  ["cuban_press", "Cuban press", "ombros", ["costas"], "isolado_ombro", [...DB, ...GYM], 2, false, ["ombro"], ["Remada alta, gire para cima e empurre", "Carga bem leve"]],
  ["remada_alta_halteres", "Remada alta com halteres", "ombros", ["costas"], "isolado_ombro", [...DB, ...GYM], 1, false, ["ombro"], ["Suba os halteres rente ao corpo", "Cotovelos até a linha dos ombros"]],
  ["remada_alta_polia", "Remada alta na polia", "ombros", ["costas"], "isolado_ombro", M("polia"), 1, false, ["ombro"], ["Barra reta na polia baixa", "Cotovelos altos"]],
  ["flexao_parada_mao", "Flexão em parada de mão na parede", "ombros", ["triceps"], "empurrar_v", BW, 3, true, ["ombro", "punho", "hipertensao", "cervical", "gestante"], ["Pés apoiados na parede", "Desça a cabeça até perto do chão com controle"]],
  ["rosca_alternada", "Rosca alternada", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Um braço de cada vez", "Gire o punho na subida"]],
  ["rosca_inclinada", "Rosca no banco inclinado", "biceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 1, false, ["ombro"], ["Braços pendurados atrás do corpo", "Alongamento máximo do bíceps"]],
  ["rosca_martelo_cruzada", "Rosca martelo cruzada", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Leve o halter em direção ao ombro oposto", "Pegada neutra"]],
  ["rosca_scott_halter", "Rosca Scott com halter", "biceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 1, false, [], ["Braço apoiado no banco", "Não estenda totalmente no fim"]],
  ["rosca_scott_barra", "Rosca Scott com barra", "biceps", [], "isolado_braco", GYM, 1, false, [], ["Axilas encaixadas no banco Scott", "Desça devagar"]],
  ["rosca_inversa", "Rosca inversa", "biceps", [], "isolado_braco", [...BB, ...GYM], 1, false, ["punho"], ["Pegada pronada (palmas para baixo)", "Trabalha também o antebraço"]],
  ["rosca_zottman", "Rosca Zottman", "biceps", [], "isolado_braco", [...DB, ...GYM], 2, false, [], ["Suba com palmas para cima", "Gire e desça com palmas para baixo"]],
  ["rosca_aranha", "Rosca aranha", "biceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 2, false, [], ["Peito apoiado no banco inclinado", "Braços pendurados para frente"]],
  ["rosca_maquina", "Rosca na máquina", "biceps", [], "isolado_braco", GYM, 1, false, [], ["Cotovelos alinhados com o eixo", "Controle a volta"]],
  ["rosca_polia_alta", "Rosca na polia alta", "biceps", [], "isolado_braco", M("polia"), 2, false, [], ["Braços abertos na altura dos ombros", "Traga as mãos até a cabeça"]],
  ["rosca_arrastada", "Rosca arrastada (drag curl)", "biceps", [], "isolado_braco", [...BB, ...GYM], 2, false, [], ["Barra desliza rente ao corpo", "Cotovelos vão para trás"]],
  ["rosca_sentado", "Rosca sentado com halteres", "biceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 1, false, [], ["Sentado com a coluna ereta", "Sem balançar"]],
  ["triceps_coice", "Tríceps coice com halter", "triceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Tronco inclinado, braço colado", "Estenda o antebraço para trás"]],
  ["triceps_frances_unilateral", "Tríceps francês unilateral", "triceps", [], "isolado_braco", [...DB, ...GYM], 1, false, ["ombro"], ["Halter atrás da cabeça", "Cotovelo apontado para cima"]],
  ["triceps_testa_halteres", "Tríceps testa com halteres", "triceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 1, false, ["punho"], ["Deitado, halteres acima do rosto", "Só o antebraço se move"]],
  ["triceps_polia_inversa", "Tríceps na polia pegada inversa", "triceps", [], "isolado_braco", M("polia"), 1, false, [], ["Palmas para cima", "Cotovelos colados"]],
  ["triceps_polia_v", "Tríceps na polia com barra V", "triceps", [], "isolado_braco", M("polia"), 1, false, [], ["Pegador em V", "Estenda totalmente"]],
  ["triceps_polia_unilateral", "Tríceps unilateral na polia", "triceps", [], "isolado_braco", M("polia"), 1, false, [], ["Um braço de cada vez", "Cotovelo parado"]],
  ["supino_fechado", "Supino fechado", "triceps", ["peito"], "empurrar_h", [...BB_BENCH, ...GYM], 2, true, ["punho", "ombro"], ["Mãos na largura dos ombros", "Cotovelos perto do corpo"]],
  ["supino_fechado_halteres", "Supino fechado com halteres", "triceps", ["peito"], "empurrar_h", [...DB_BENCH, ...GYM], 1, true, [], ["Halteres encostados um no outro", "Cotovelos rentes"]],
  ["mergulho_triceps", "Mergulho nas paralelas (tríceps)", "triceps", ["peito", "ombros"], "empurrar_h", [["paralelas"], ["academia"]], 3, true, ["ombro"], ["Tronco reto", "Desça até 90° no cotovelo"]],
  ["mergulho_maquina", "Mergulho na máquina", "triceps", ["peito"], "empurrar_h", GYM, 1, true, [], ["Costas apoiadas", "Empurre para baixo até estender"]],
  ["triceps_maquina", "Tríceps na máquina", "triceps", [], "isolado_braco", GYM, 1, false, [], ["Cotovelos apoiados", "Estenda sem tirar o apoio"]],
  ["flexao_fechada", "Flexão fechada (tríceps)", "triceps", ["peito"], "empurrar_h", BW, 2, true, ["punho"], ["Mãos abaixo dos ombros", "Cotovelos rentes ao corpo"]],
  ["triceps_testa_elastico", "Tríceps testa com elástico", "triceps", [], "isolado_braco", BAND, 1, false, [], ["Elástico preso atrás da cabeça", "Estenda os braços para cima"]],
  ["tate_press", "Tate press", "triceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 2, false, ["punho"], ["Halteres descem até tocar o peito", "Cotovelos abertos para os lados"]],
  ["agachamento_halteres", "Agachamento com halteres", "quadriceps", ["gluteos"], "agachar", [...DB, ...GYM], 1, true, [], ["Halteres ao lado do corpo", "Tronco ereto"]],
  ["agachamento_kb_duplo", "Agachamento frontal com 2 kettlebells", "quadriceps", ["gluteos", "core"], "agachar", KB, 2, true, ["punho"], ["Kettlebells apoiados nos antebraços", "Cotovelos altos"]],
  ["agachamento_banco_barra", "Agachamento no banco com barra", "quadriceps", ["gluteos"], "agachar", [...BB_BENCH, ...GYM], 2, true, ["lombar"], ["Sente de leve no banco", "Suba empurrando o chão"]],
  ["hack_fechado", "Hack com pés juntos", "quadriceps", [], "agachar", M("leg_press"), 2, true, ["joelho"], ["Pés próximos e mais baixos", "Foco no quadríceps"]],
  ["agachamento_maquina", "Agachamento na máquina", "quadriceps", ["gluteos"], "agachar", GYM, 1, true, [], ["Costas apoiadas", "Desça controlando"]],
  ["afundo_barra", "Afundo com barra", "quadriceps", ["gluteos"], "unilateral_perna", [...BB, ...GYM], 3, true, ["joelho", "lombar"], ["Barra nas costas", "Passo largo à frente"]],
  ["subida_banco_halteres", "Subida no banco com halteres", "gluteos", ["quadriceps"], "unilateral_perna", [...DB_BENCH, ...GYM], 2, true, [], ["Suba com a perna de cima fazendo a força", "Desça controlado"]],
  ["extensora_unilateral", "Cadeira extensora unilateral", "quadriceps", [], "isolado_perna", M("extensora_flexora"), 1, false, ["joelho"], ["Uma perna de cada vez", "Segure 1 segundo em cima"]],
  ["flexora_em_pe", "Flexora em pé", "posterior", [], "isolado_perna", GYM, 1, false, [], ["Quadril parado", "Puxe o calcanhar em direção ao glúteo"]],
  ["flexora_elastico", "Flexora com elástico", "posterior", [], "isolado_perna", BAND, 1, false, [], ["Sentado, elástico preso à frente", "Puxe o calcanhar para baixo e para trás"]],
  ["terra_sumo", "Levantamento terra sumô", "gluteos", ["posterior", "quadriceps"], "dobrar_quadril", [...BB, ...GYM], 3, true, ["lombar", "hipertensao"], ["Pés bem afastados, pontas para fora", "Pegada por dentro das pernas"]],
  ["stiff_pernas_retas", "Stiff com barra (pernas estendidas)", "posterior", ["gluteos"], "dobrar_quadril", [...BB, ...GYM], 2, true, ["lombar"], ["Joelhos quase estendidos", "Desça só até onde a coluna fica neutra"]],
  ["bom_dia_barra", "Bom dia com barra", "posterior", ["gluteos", "costas"], "dobrar_quadril", [...BB, ...GYM], 3, true, ["lombar"], ["Barra nas costas", "Incline o tronco levando o quadril para trás"]],
  ["glute_ham", "Flexão nórdica na máquina (GHR)", "posterior", ["gluteos"], "isolado_perna", GYM, 3, false, ["joelho"], ["Pés presos, joelhos na almofada", "Desça e suba com o posterior"]],
  ["pull_through", "Pull through na polia", "gluteos", ["posterior"], "dobrar_quadril", M("polia"), 1, true, [], ["De costas para a polia baixa, corda entre as pernas", "Estenda o quadril contraindo o glúteo"]],
  ["ponte_barra", "Ponte de glúteo com barra", "gluteos", ["posterior"], "dobrar_quadril", [...BB, ...GYM], 1, true, [], ["Deitado no chão, barra sobre o quadril", "Suba contraindo o glúteo"]],
  ["ponte_elastico", "Ponte de glúteo com elástico", "gluteos", ["posterior"], "dobrar_quadril", BAND, 1, false, [], ["Elástico acima dos joelhos", "Empurre os joelhos para fora ao subir"]],
  ["coice_quatro_apoios", "Coice de glúteo em quatro apoios", "gluteos", [], "isolado_perna", BW, 1, false, [], ["Joelho dobrado, empurre o pé para o teto", "Não arqueie a lombar"]],
  ["extensao_quadril_elastico", "Extensão de quadril com elástico", "gluteos", ["posterior"], "isolado_perna", BAND, 1, false, [], ["Elástico no tornozelo, preso à frente", "Leve a perna para trás"]],
  ["elevacao_perna_gluteo", "Elevação de perna deitado de bruços", "gluteos", ["posterior"], "isolado_perna", BW, 1, false, [], ["De bruços, perna estendida", "Suba a perna contraindo o glúteo"]],
  ["panturrilha_sentado_halter", "Panturrilha sentado com halter", "panturrilha", [], "isolado_perna", [...DB, ...GYM], 1, false, [], ["Halter sobre o joelho", "Ponta do pé num apoio"]],
  ["panturrilha_smith", "Panturrilha no Smith", "panturrilha", [], "isolado_perna", M("smith"), 1, false, [], ["Ponta dos pés num step", "Amplitude total"]],
  ["panturrilha_barra", "Panturrilha em pé com barra", "panturrilha", [], "isolado_perna", [...BB, ...GYM], 2, false, [], ["Barra nas costas", "Suba na ponta dos pés"]],
  ["panturrilha_burrinho", "Panturrilha burrinho", "panturrilha", [], "isolado_perna", GYM, 2, false, ["lombar"], ["Tronco inclinado à frente", "Quadril sobre os pés"]],
  ["panturrilha_elastico", "Panturrilha com elástico", "panturrilha", [], "isolado_perna", BAND, 1, false, [], ["Sentado, elástico na ponta do pé", "Empurre como num pedal"]],
  ["abdominal_infra", "Abdominal infra (reverso)", "core", [], "core", BW, 1, false, ["gestante"], ["Deitado, joelhos dobrados", "Leve os joelhos ao peito tirando o quadril do chão"]],
  ["abdominal_obliquo", "Abdominal oblíquo", "core", [], "core", BW, 1, false, ["cervical", "gestante"], ["Deitado de lado com joelhos dobrados", "Suba o tronco em direção ao quadril"]],
  ["rotacao_russa", "Rotação russa", "core", [], "core", BW, 2, false, ["lombar", "gestante"], ["Sentado, tronco inclinado para trás", "Gire de um lado para o outro"]],
  ["abdominal_canivete", "Abdominal canivete", "core", [], "core", BW, 2, false, ["lombar", "gestante"], ["Deitado estendido", "Suba braços e pernas ao mesmo tempo"]],
  ["abdominal_grupado", "Abdominal grupado", "core", [], "core", BW, 1, false, ["gestante"], ["Joelhos e tronco se encontram no meio", "Movimento controlado"]],
  ["elevacao_joelhos_paralelas", "Elevação de joelhos nas paralelas", "core", [], "core", [["paralelas"], ["academia"]], 2, false, ["ombro"], ["Apoiado nos antebraços", "Suba os joelhos até o quadril"]],
  ["abdominal_bola_pernas", "Encolhimento de pernas na bola suíça", "core", ["ombros"], "core", [["bola_suica"]], 2, false, ["punho", "gestante"], ["Prancha com os pés na bola", "Traga os joelhos ao peito"]],
  ["abdominal_bola", "Abdominal na bola suíça", "core", [], "core", [["bola_suica"]], 1, false, ["gestante"], ["Lombar apoiada na bola", "Suba só o tronco"]],
  ["lenhador_polia", "Lenhador na polia", "core", ["ombros"], "core", M("polia"), 1, false, ["lombar"], ["Puxe o cabo do alto para baixo cruzando o corpo", "Gire o tronco, não os braços"]],
  ["pallof_rotacao", "Pallof com rotação", "core", [], "core", [...BAND, ...M("polia")], 2, false, [], ["Empurre à frente e gire levemente", "Volte sem deixar o cabo puxar"]],
  ["flexao_lateral_halter", "Flexão lateral com halter", "core", [], "core", [...DB, ...GYM], 1, false, ["lombar"], ["Halter numa mão", "Incline para o lado e volte"]],
  ["tesourinha", "Tesourinha (flutter kicks)", "core", [], "core", BW, 1, false, ["lombar", "gestante"], ["Lombar colada no chão", "Pernas alternam para cima e para baixo"], "seg"],
  ["abdominal_corda_pe", "Abdominal na corda em pé", "core", [], "core", M("polia"), 1, false, [], ["De costas para a polia alta", "Enrole o tronco para baixo"]],
  ["kb_moinho", "Moinho com kettlebell", "core", ["ombros"], "core", KB, 3, false, ["lombar", "ombro"], ["Kettlebell acima da cabeça", "Desça a outra mão até o pé"]],
  ["rollout_barra", "Rollout com barra (de joelhos)", "core", ["ombros"], "core", [...BB, ...GYM], 3, false, ["lombar", "gestante"], ["De joelhos segurando a barra", "Role à frente e volte com o abdômen"]],
  ["toque_calcanhar", "Toque no calcanhar", "core", [], "core", BW, 1, false, ["cervical", "gestante"], ["Deitado, joelhos dobrados", "Alcance um calcanhar de cada vez"]],
  ["elevacao_quadril_infra", "Elevação de quadril (infra)", "core", [], "core", BW, 1, false, ["gestante"], ["Pernas para cima", "Tire o quadril do chão em direção ao teto"]],
  ["corda_naval", "Corda naval", "cardio", ["ombros", "core"], "condicionamento", GYM, 2, true, [], ["Joelhos semiflexionados", "Ondas rápidas e alternadas"], "seg"],
  ["bike_reclinada", "Bike reclinada", "cardio", ["quadriceps"], "condicionamento", [["cardio_maquina"], ["academia"]], 1, false, [], ["Costas apoiadas", "Ótima para quem tem dor lombar"], "seg"],
  ["trote_esteira", "Trote na esteira", "cardio", [], "condicionamento", [["cardio_maquina"], ["academia"]], 1, false, ["joelho"], ["Passada curta e leve", "Ritmo em que ainda dá para falar"], "seg"],
  ["salto_tesoura", "Salto afundo (tesoura)", "cardio", ["quadriceps", "gluteos"], "condicionamento", BW, 3, true, ["joelho", "gestante", "hipertensao"], ["Troque as pernas no ar", "Aterrisse macio"]],
  ["salto_caixa", "Salto na caixa", "cardio", ["quadriceps", "gluteos"], "condicionamento", [["banco"], ["academia"]], 2, true, ["joelho", "gestante"], ["Salte com os dois pés", "Desça com calma, não pule para trás"]],
  ["salto_distancia", "Salto em distância", "cardio", ["quadriceps", "gluteos"], "condicionamento", BW, 2, true, ["joelho", "gestante"], ["Balance os braços", "Aterrisse com joelhos flexionados"]],
  ["salto_grupado", "Salto grupado", "cardio", ["quadriceps"], "condicionamento", BW, 3, true, ["joelho", "gestante", "hipertensao"], ["Leve os joelhos ao peito no ar", "Aterrisse macio"]],
  ["kb_arranco", "Arranco com kettlebell", "cardio", ["ombros", "gluteos"], "condicionamento", KB, 3, true, ["ombro", "lombar"], ["Do meio das pernas até acima da cabeça num movimento", "Força vem do quadril"]],
  ["kb_clean", "Clean com kettlebell", "cardio", ["gluteos", "ombros"], "condicionamento", KB, 2, true, ["lombar"], ["Kettlebell sobe até o ombro", "Quadril faz a força"]],

  // ---------------- Ainda mais opções ----------------
  ["supino_declinado_barra", "Supino declinado com barra", "peito", ["triceps"], "empurrar_h", [...BB_BENCH, ...GYM], 2, true, [], ["Pés presos no banco declinado", "Barra desce na parte baixa do peito"]],
  ["supino_aberto_barra", "Supino com pegada aberta", "peito", ["ombros"], "empurrar_h", [...BB_BENCH, ...GYM], 2, true, ["ombro"], ["Mãos mais abertas que o normal", "Desça controlando, sem quicar no peito"]],
  ["supino_inclinado_neutro", "Supino inclinado com pegada neutra", "peito", ["ombros", "triceps"], "empurrar_h", [...DB_BENCH, ...GYM], 1, true, [], ["Banco a 30°, palmas viradas uma para a outra", "Bom para quem sente o ombro"]],
  ["crucifixo_inclinado_polia", "Crucifixo inclinado na polia", "peito", [], "empurrar_h", M("polia"), 2, false, [], ["Banco inclinado entre as polias baixas", "Feche os braços em arco acima do peito"]],
  ["supino_inclinado_polia", "Supino inclinado na polia", "peito", ["ombros", "triceps"], "empurrar_h", M("polia"), 2, true, [], ["Banco inclinado entre as polias", "Empurre até estender os braços à frente"]],
  ["crucifixo_declinado", "Crucifixo declinado com halteres", "peito", [], "empurrar_h", [...DB_BENCH, ...GYM], 2, false, ["ombro"], ["Banco declinado, cotovelos levemente dobrados", "Abra até alongar a parte baixa do peito"]],
  ["flexao_pes_bola", "Flexão com pés na bola suíça", "peito", ["core", "triceps"], "empurrar_h", [["bola_suica"]], 3, true, ["punho"], ["Canelas sobre a bola, corpo reto", "Desça o peito sem deixar o quadril cair"]],
  ["flexao_relogio", "Flexão relógio", "peito", ["ombros", "core"], "empurrar_h", BW, 2, true, ["punho"], ["Após cada flexão, caminhe as mãos um pouco para o lado", "Dê a volta completa como um ponteiro"]],
  ["supino_articulado", "Supino articulado sentado", "peito", ["triceps"], "empurrar_h", M("maquinas_peito_ombro"), 1, true, [], ["Pegadas na altura do meio do peito", "Empurre sem travar os cotovelos"]],
  ["supino_declinado_smith", "Supino declinado no Smith", "peito", ["triceps"], "empurrar_h", M("smith"), 2, true, [], ["Banco declinado embaixo da barra", "Barra desce na parte baixa do peito"]],
  ["pullover_flexionado", "Pullover com halter (braços flexionados)", "peito", ["costas"], "empurrar_h", [...DB_BENCH, ...GYM], 2, false, ["ombro"], ["Deitado, halter acima do peito", "Leve para trás da cabeça dobrando os cotovelos e volte"]],
  ["flexao_um_braco", "Flexão com um braço", "peito", ["core", "triceps"], "empurrar_h", BW, 3, true, ["punho", "ombro"], ["Pés afastados para equilibrar", "Desça devagar com o abdômen firme"]],
  ["flexao_inclinada_aberta", "Flexão inclinada aberta", "peito", ["ombros"], "empurrar_h", BW, 1, true, [], ["Mãos num banco, bem abertas", "Corpo reto da cabeça aos pés"]],
  ["volta_mundo_halteres", "Volta ao mundo com halteres", "peito", ["ombros"], "empurrar_h", [...DB_BENCH, ...GYM], 2, false, ["ombro"], ["Deitado, halteres leves nas coxas", "Faça um arco largo até acima da cabeça e volte"]],
  ["supino_elastico", "Supino com elástico", "peito", ["triceps"], "empurrar_h", BAND, 1, true, [], ["Elástico passando pelas costas", "Empurre à frente como num supino"]],
  ["supino_chao_barra", "Supino no chão com barra", "peito", ["triceps"], "empurrar_h", [...BB, ...GYM], 2, true, [], ["Deitado no chão, cotovelos tocam o chão", "Pausa curta e empurre"]],
  ["kb_supino_chao", "Supino no chão com kettlebell", "peito", ["triceps"], "empurrar_h", KB, 1, true, [], ["Deitado, kettlebell apoiado no antebraço", "Empurre um braço de cada vez"]],
  ["remada_alta_unilateral_polia", "Remada unilateral ajoelhado na polia alta", "costas", ["biceps"], "puxar_h", M("polia"), 1, false, [], ["Ajoelhado de frente para a polia alta", "Puxe o cotovelo para trás e para baixo"]],
  ["remada_unilateral_polia_pe", "Remada unilateral na polia baixa em pé", "costas", ["biceps", "core"], "puxar_h", M("polia"), 1, false, [], ["Pernas afastadas, uma à frente", "Puxe até a cintura sem girar o tronco"]],
  ["kb_remada_dupla", "Remada curvada com dois kettlebells", "costas", ["biceps"], "puxar_h", KB, 2, true, ["lombar"], ["Tronco inclinado, costas retas", "Puxe os dois kettlebells até a cintura"]],
  ["remada_t_apoiada", "Remada T com apoio no peito", "costas", ["biceps"], "puxar_h", M("maquinas_costas"), 1, true, [], ["Peito apoiado no aparelho", "Puxe apertando as escápulas"]],
  ["remada_landmine_unilateral", "Remada unilateral na barra livre (landmine)", "costas", ["biceps"], "puxar_h", [...BB, ...GYM], 2, true, ["lombar"], ["Uma ponta da barra presa no canto", "Puxe a outra ponta até a cintura"]],
  ["barra_com_carga", "Barra fixa com carga", "costas", ["biceps"], "puxar_v", PULLUP, 3, true, ["ombro"], ["Peso preso num cinto ou entre os pés", "Suba até o queixo passar a barra"]],
  ["barra_pegada_mista", "Barra fixa com pegada mista", "costas", ["biceps"], "puxar_v", PULLUP, 3, true, ["ombro"], ["Uma mão pronada e outra supinada", "Troque as mãos a cada série"]],
  ["puxada_cruzada", "Puxada cruzada na polia alta", "costas", [], "puxar_v", M("polia"), 2, false, [], ["Segure os cabos cruzados acima da cabeça", "Puxe os cotovelos para baixo e para os lados"]],
  ["pullover_barra", "Pullover com barra", "costas", ["peito"], "puxar_v", [...BB_BENCH, ...GYM], 2, false, ["ombro"], ["Deitado, barra acima do peito com cotovelos dobrados", "Leve atrás da cabeça e puxe de volta com as costas"]],
  ["retracao_escapular", "Retração escapular no banco inclinado", "costas", ["ombros"], "puxar_h", [...DB_BENCH, ...GYM], 1, false, [], ["De bruços no banco inclinado, braços estendidos", "Aperte as escápulas sem dobrar os cotovelos"]],
  ["encolhimento_polia", "Encolhimento na polia", "costas", ["ombros"], "isolado_ombro", M("polia"), 1, false, ["cervical"], ["Cabos nas polias baixas", "Suba os ombros e segure 1 segundo"]],
  ["encolhimento_smith", "Encolhimento no Smith", "costas", ["ombros"], "isolado_ombro", M("smith"), 1, false, ["cervical"], ["Barra por trás do corpo", "Suba os ombros sem dobrar os cotovelos"]],
  ["remada_alta_elastico", "Remada alta com elástico", "ombros", ["costas"], "isolado_ombro", BAND, 1, false, ["ombro"], ["Pise no elástico", "Suba as mãos rente ao corpo até o peito"]],
  ["remada_alta_smith", "Remada alta no Smith", "ombros", ["costas"], "isolado_ombro", M("smith"), 1, false, ["ombro"], ["Pegada na largura dos ombros", "Cotovelos sobem até a linha dos ombros"]],
  ["remada_alta_barra", "Remada alta com barra", "ombros", ["costas"], "isolado_ombro", [...BB, ...GYM], 2, false, ["ombro"], ["Pegada na largura dos ombros", "Cotovelos lideram a subida"]],
  ["desenvolvimento_pe_halteres", "Desenvolvimento em pé com halteres", "ombros", ["triceps", "core"], "empurrar_v", [...DB, ...GYM], 2, true, ["ombro"], ["Em pé, abdômen e glúteos firmes", "Empurre sem arquear a lombar"]],
  ["desenvolvimento_neutro", "Desenvolvimento com pegada neutra", "ombros", ["triceps"], "empurrar_v", [...DB, ...GYM], 1, true, [], ["Palmas viradas uma para a outra", "Mais amigável para o ombro"]],
  ["desenvolvimento_alternado", "Desenvolvimento alternado em pé", "ombros", ["triceps", "core"], "empurrar_v", [...DB, ...GYM], 1, true, ["ombro"], ["Um braço sobe enquanto o outro espera em cima", "Tronco parado"]],
  ["scaption", "Elevação em Y com halteres", "ombros", [], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Braços sobem em diagonal, polegares para cima", "Até a altura dos ombros"]],
  ["elevacao_lateral_sentado", "Elevação lateral sentado", "ombros", [], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Sentado na ponta do banco", "Sem balançar o tronco"]],
  ["elevacao_lateral_polia_sentado", "Elevação lateral sentado na polia", "ombros", [], "isolado_ombro", M("polia"), 2, false, [], ["Sentado ao lado da polia baixa", "Suba o braço até a linha do ombro"]],
  ["elevacao_frontal_dupla", "Elevação frontal com dois halteres", "ombros", [], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Os dois braços sobem juntos", "Até a altura dos olhos"]],
  ["elevacao_lateral_frontal", "Elevação lateral + frontal", "ombros", [], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Uma repetição lateral, outra frontal", "Carga leve e controle"]],
  ["crucifixo_inverso_deitado", "Crucifixo inverso deitado no banco inclinado", "ombros", ["costas"], "isolado_ombro", [...DB_BENCH, ...GYM], 1, false, [], ["De bruços no banco inclinado", "Abra os braços até a linha dos ombros"]],
  ["crucifixo_inverso_sentado", "Crucifixo inverso sentado", "ombros", ["costas"], "isolado_ombro", [...DB, ...GYM], 1, false, [], ["Sentado, tronco inclinado sobre as coxas", "Abra os braços com cotovelos levemente dobrados"]],
  ["remada_posterior_corda", "Remada de posterior de ombro na corda", "ombros", ["costas"], "isolado_ombro", M("polia"), 1, false, [], ["Corda na polia na altura do peito", "Puxe em direção ao rosto com cotovelos altos"]],
  ["crucifixo_inverso_rotacao", "Crucifixo inverso com rotação externa", "ombros", ["costas"], "isolado_ombro", [...DB, ...GYM], 2, false, [], ["Tronco inclinado, abra os braços", "No alto, gire as mãos para fora"]],
  ["rotacao_interna_elastico", "Rotação interna com elástico", "ombros", [], "isolado_ombro", BAND, 1, false, [], ["Cotovelo colado ao corpo a 90°", "Traga a mão para a barriga"]],
  ["rotacao_externa_polia", "Rotação externa na polia", "ombros", [], "isolado_ombro", M("polia"), 1, false, [], ["Cotovelo colado ao corpo a 90°", "Gire a mão para fora, devagar"]],
  ["kb_desenvolvimento_duplo", "Desenvolvimento com dois kettlebells", "ombros", ["triceps", "core"], "empurrar_v", KB, 2, true, ["ombro"], ["Kettlebells apoiados nos antebraços", "Empurre os dois juntos acima da cabeça"]],
  ["kb_desenvolvimento_sentado", "Desenvolvimento sentado com kettlebell", "ombros", ["triceps"], "empurrar_v", KB, 1, true, ["ombro"], ["Sentado com a coluna reta", "Empurre um braço de cada vez"]],
  ["desenvolvimento_landmine", "Desenvolvimento na barra livre (landmine)", "ombros", ["peito", "core"], "empurrar_v", [...BB, ...GYM], 1, true, [], ["Ponta da barra presa no canto", "Empurre para cima e à frente com um braço"]],
  ["rosca_martelo_alternada", "Rosca martelo alternada", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Palmas viradas para o corpo", "Um braço de cada vez, sem balançar"]],
  ["rosca_w", "Rosca com barra W", "biceps", [], "isolado_braco", [...BB, ...GYM], 1, false, [], ["Pegada na parte angulada da barra", "Cotovelos parados ao lado do corpo"]],
  ["rosca_w_fechada", "Rosca barra W pegada fechada", "biceps", [], "isolado_braco", [...BB, ...GYM], 1, false, [], ["Mãos próximas na barra W", "Suba sem levar os cotovelos à frente"]],
  ["rosca_barra_aberta", "Rosca direta pegada aberta", "biceps", [], "isolado_braco", [...BB, ...GYM], 1, false, [], ["Mãos mais abertas que os ombros", "Trabalha mais a parte interna do bíceps"]],
  ["rosca_martelo_inclinada", "Rosca martelo no banco inclinado", "biceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 2, false, [], ["Costas no banco inclinado, braços soltos", "Suba com as palmas viradas para dentro"]],
  ["rosca_scott_maquina", "Rosca Scott na máquina", "biceps", [], "isolado_braco", GYM, 1, false, [], ["Braços apoiados no aparelho", "Desça devagar"]],
  ["rosca_inversa_polia", "Rosca inversa na polia", "biceps", [], "isolado_braco", M("polia"), 1, false, [], ["Pegada por cima (palmas para baixo)", "Trabalha antebraço e braquial"]],
  ["rosca_unilateral_polia", "Rosca unilateral na polia", "biceps", [], "isolado_braco", M("polia"), 1, false, [], ["De lado para a polia baixa", "Um braço de cada vez, cotovelo fixo"]],
  ["rosca_scott_dupla", "Rosca Scott com dois halteres", "biceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 1, false, [], ["Braços apoiados no banco Scott", "Suba os dois halteres juntos"]],
  ["rosca_deitado", "Rosca deitado no banco", "biceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 2, false, [], ["Deitado num banco alto, braços soltos para baixo", "Suba sem mexer os cotovelos"]],
  ["rosca_concentrada_pe", "Rosca concentrada em pé", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Tronco inclinado, braço solto", "Suba o halter em direção ao ombro"]],
  ["rosca_inversa_halteres", "Rosca inversa com halteres", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, [], ["Palmas viradas para trás", "Suba devagar, punho firme"]],
  ["rosca_punho", "Rosca de punho (antebraço)", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, ["punho"], ["Antebraços apoiados nas coxas, palmas para cima", "Só o punho se move"]],
  ["rosca_punho_inversa", "Rosca de punho invertida (antebraço)", "biceps", [], "isolado_braco", [...DB, ...GYM], 1, false, ["punho"], ["Antebraços apoiados, palmas para baixo", "Suba o dorso da mão"]],
  ["supino_jm", "Supino JM", "triceps", ["peito"], "isolado_braco", [...BB_BENCH, ...GYM], 3, true, ["ombro", "punho"], ["Pegada fechada, barra desce em direção ao queixo", "Cotovelos à frente, empurre com o tríceps"]],
  ["mergulho_banco_carga", "Mergulho no banco com carga", "triceps", ["peito"], "isolado_braco", [["banco", "anilhas"], ["academia"]], 2, false, ["ombro"], ["Anilha no colo, mãos no banco", "Desça até 90° nos cotovelos"]],
  ["triceps_barra_corpo", "Tríceps com peso do corpo na barra", "triceps", ["core"], "isolado_braco", M("smith"), 2, false, ["punho"], ["Barra na altura do peito, corpo inclinado", "Dobre os cotovelos levando a testa à barra"]],
  ["flexao_fechada_halter", "Flexão fechada sobre halter", "triceps", ["peito"], "isolado_braco", [...DB, ...GYM], 2, true, ["punho"], ["Mãos juntas sobre um halter deitado", "Cotovelos rentes ao corpo"]],
  ["flexao_inclinada_fechada", "Flexão inclinada fechada", "triceps", ["peito"], "isolado_braco", BW, 1, true, [], ["Mãos juntas num banco ou mesa", "Cotovelos para trás, rente ao corpo"]],
  ["triceps_frances_sentado", "Tríceps francês sentado com halter", "triceps", [], "isolado_braco", [...DB, ...GYM], 1, false, ["ombro"], ["Sentado, halter atrás da cabeça com as duas mãos", "Cotovelos apontando para cima"]],
  ["triceps_coice_duplo", "Tríceps coice com dois halteres", "triceps", [], "isolado_braco", [...DB, ...GYM], 1, false, ["lombar"], ["Tronco inclinado, cotovelos colados ao corpo", "Estenda os dois braços para trás"]],
  ["triceps_polia_baixa", "Tríceps na polia baixa de costas", "triceps", [], "isolado_braco", M("polia"), 1, false, ["ombro"], ["De costas para a polia baixa", "Estenda os braços acima da cabeça"]],
  ["triceps_polia_ajoelhado", "Tríceps francês ajoelhado na polia", "triceps", [], "isolado_braco", M("polia"), 2, false, ["ombro"], ["Ajoelhado de costas para a polia", "Estenda os braços à frente e acima"]],
  ["triceps_testa_polia", "Tríceps testa na polia", "triceps", [], "isolado_braco", M("polia"), 2, false, ["punho"], ["Deitado com a cabeça perto da polia baixa", "Só os antebraços se movem"]],
  ["triceps_toalha", "Tríceps com toalha", "triceps", [], "isolado_braco", BW, 1, false, [], ["Toalha acima da cabeça, a outra mão puxa para baixo resistindo", "Estenda o braço vencendo a resistência"]],
  ["triceps_testa_declinado", "Tríceps testa declinado com halteres", "triceps", [], "isolado_braco", [...DB_BENCH, ...GYM], 2, false, ["punho"], ["Banco declinado", "Halteres descem ao lado da cabeça"]],
  ["supino_fechado_smith", "Supino fechado no Smith", "triceps", ["peito"], "isolado_braco", M("smith"), 2, true, ["punho"], ["Mãos na largura dos ombros", "Cotovelos rentes ao corpo"]],
  ["triceps_elastico_acima", "Tríceps acima da cabeça com elástico", "triceps", [], "isolado_braco", BAND, 1, false, ["ombro"], ["Pise no elástico e segure atrás da cabeça", "Estenda os braços para cima"]],
  ["agachamento_banco_halteres", "Agachamento até o banco com halteres", "quadriceps", ["gluteos"], "agachar", [...DB_BENCH, ...GYM], 1, true, [], ["Sente de leve no banco e suba", "Ótimo para aprender a profundidade"]],
  ["subida_banco_barra", "Subida no banco com barra", "quadriceps", ["gluteos"], "unilateral_perna", [...BB_BENCH, ...GYM], 3, true, ["joelho"], ["Barra nas costas", "Suba empurrando o pé que está no banco"]],
  ["afundo_caminhando_barra", "Afundo caminhando com barra", "quadriceps", ["gluteos"], "unilateral_perna", [...BB, ...GYM], 3, true, ["joelho"], ["Barra nas costas, passos longos", "Joelho de trás quase toca o chão"]],
  ["afundo_deficit", "Afundo reverso com déficit", "quadriceps", ["gluteos"], "unilateral_perna", [...BB, ...GYM], 3, true, ["joelho"], ["Em cima de um step, passo para trás", "Amplitude maior para glúteo"]],
  ["agachamento_zercher", "Agachamento Zercher", "quadriceps", ["gluteos", "core"], "agachar", [...BB, ...GYM], 3, true, ["lombar"], ["Barra apoiada na dobra dos cotovelos", "Tronco ereto, desça controlando"]],
  ["agachamento_aberto_barra", "Agachamento com barra base aberta", "quadriceps", ["gluteos"], "agachar", [...BB, ...GYM], 2, true, ["joelho"], ["Pés bem afastados, pontas para fora", "Joelhos acompanham as pontas dos pés"]],
  ["bulgaro_trx", "Agachamento búlgaro no TRX", "quadriceps", ["gluteos"], "unilateral_perna", [["trx"]], 2, true, ["joelho"], ["Pé de trás na alça do TRX", "Desça reto, tronco firme"]],
  ["terra_hexagonal", "Levantamento terra com barra hexagonal", "gluteos", ["quadriceps", "posterior"], "dobrar_quadril", GYM, 2, true, ["lombar"], ["Dentro da barra, pegadas neutras", "Empurre o chão e suba com o peito aberto"]],
  ["sissy_squat", "Agachamento sissy", "quadriceps", [], "isolado_perna", BW, 3, false, ["joelho"], ["Segure num apoio, suba na ponta dos pés", "Joelhos vão à frente e o tronco inclina para trás"]],
  ["flexao_quadril_elastico", "Flexão de quadril com elástico", "quadriceps", ["core"], "isolado_perna", BAND, 1, false, [], ["Elástico no pé, preso atrás", "Suba o joelho à frente"]],
  ["flexora_deslizante", "Flexora deslizante no chão", "posterior", ["gluteos"], "isolado_perna", BW, 2, false, ["joelho"], ["Deitado, calcanhar sobre uma toalha no piso liso", "Puxe o calcanhar em direção ao glúteo"]],
  ["hiperextensao_reversa", "Hiperextensão reversa", "gluteos", ["posterior"], "dobrar_quadril", GYM, 2, false, [], ["Tronco apoiado, pernas soltas", "Suba as pernas contraindo o glúteo"]],
  ["afundo_passando_kb", "Afundo passando o kettlebell", "quadriceps", ["gluteos", "core"], "unilateral_perna", KB, 2, true, ["joelho"], ["No fundo do afundo, passe o kettlebell por baixo da perna", "Alterne as pernas"]],
  ["ponte_bola", "Ponte de glúteo na bola suíça", "gluteos", ["posterior"], "dobrar_quadril", [["bola_suica"]], 1, false, [], ["Pés sobre a bola", "Suba o quadril sem deixar a bola rolar"]],
  ["subida_banco_joelho", "Subida no banco com elevação de joelho", "gluteos", ["quadriceps"], "unilateral_perna", [["banco"], ["academia"]], 1, true, ["joelho"], ["Suba no banco e traga o outro joelho à frente", "Desça controlando"]],
  ["aducao_elastico", "Adução de quadril com elástico", "quadriceps", [], "isolado_perna", BAND, 1, false, [], ["Elástico preso de lado no tornozelo", "Traga a perna para dentro cruzando à frente"]],
  ["cadeira_adutora", "Cadeira adutora", "quadriceps", [], "isolado_perna", M("abdutora"), 1, false, [], ["Parte interna das coxas nas almofadas", "Feche as pernas e volte devagar"]],
  ["aducao_polia", "Adução na polia", "quadriceps", [], "isolado_perna", M("polia"), 1, false, [], ["Tornozeleira na polia baixa", "Cruze a perna à frente da outra"]],
  ["panturrilha_pe_halter", "Panturrilha em pé com halteres", "panturrilha", [], "isolado_perna", [...DB, ...GYM], 1, false, [], ["Halteres ao lado do corpo", "Suba o máximo na ponta dos pés"]],
  ["panturrilha_sentado_barra", "Panturrilha sentado com barra", "panturrilha", [], "isolado_perna", [...BB_BENCH, ...GYM], 1, false, [], ["Barra sobre os joelhos com uma toalha", "Ponta dos pés num apoio"]],
  ["panturrilha_prensa", "Panturrilha na máquina", "panturrilha", [], "isolado_perna", M("panturrilha_maquina"), 1, false, [], ["Pontas dos pés na plataforma", "Amplitude total, pausa em cima"]],
  ["tibial_smith", "Elevação de ponta de pé (tibial)", "panturrilha", [], "isolado_perna", M("smith"), 1, false, [], ["Calcanhares apoiados, ponta dos pés para fora", "Suba as pontas dos pés em direção à canela"]],
  ["hiperextensao_bola", "Hiperextensão na bola suíça", "gluteos", ["posterior", "costas"], "dobrar_quadril", [["bola_suica"]], 1, false, [], ["Quadril sobre a bola, pés na parede", "Suba o tronco até ficar alinhado"]],
  ["terra_parcial", "Terra parcial (rack pull)", "costas", ["gluteos", "posterior"], "dobrar_quadril", GYM, 2, true, ["lombar"], ["Barra apoiada no rack na altura do joelho", "Suba estendendo o quadril, peito aberto"]],
  ["terra_deficit", "Terra com déficit", "posterior", ["gluteos", "costas"], "dobrar_quadril", [...BB, ...GYM], 3, true, ["lombar"], ["Em cima de uma anilha ou step baixo", "Mais amplitude na saída do chão"]],
  ["abdominal_completo", "Abdominal completo", "core", [], "core", BW, 1, false, ["lombar", "gestante"], ["Pés no chão, suba o tronco inteiro", "Desça devagar"]],
  ["abdominal_cruzado", "Abdominal cruzado", "core", [], "core", BW, 1, false, ["cervical", "gestante"], ["Cotovelo vai em direção ao joelho oposto", "Alterne os lados"]],
  ["abdominal_pernas_bola", "Abdominal com pernas na bola", "core", [], "core", [["bola_suica"]], 1, false, ["gestante"], ["Panturrilhas sobre a bola", "Suba só o tronco"]],
  ["abdominal_declinado", "Abdominal declinado", "core", [], "core", [["banco"], ["academia"]], 2, false, ["lombar", "gestante"], ["Pés presos no banco declinado", "Suba o tronco sem puxar o pescoço"]],
  ["infra_declinado", "Abdominal infra no banco declinado", "core", [], "core", [["banco"], ["academia"]], 2, false, ["gestante"], ["Segure o banco atrás da cabeça", "Leve os joelhos ao peito tirando o quadril"]],
  ["cotovelo_joelho", "Cotovelo no joelho", "core", [], "core", BW, 1, false, ["gestante"], ["Deitado, traga cotovelo e joelho opostos juntos", "Ritmo controlado"]],
  ["canivete_barra", "Canivete pendurado na barra", "core", [], "core", PULLUP, 3, false, ["ombro", "lombar"], ["Pendurado, suba as pernas retas até a barra", "Desça sem balançar"]],
  ["recolhimento_pernas", "Recolhimento de pernas no chão", "core", [], "core", BW, 1, false, ["gestante"], ["Sentado, apoiado nas mãos", "Traga os joelhos ao peito e estenda"]],
  ["recolhimento_banco", "Recolhimento de pernas sentado no banco", "core", [], "core", [["banco"], ["academia"]], 1, false, ["gestante"], ["Sentado na ponta do banco", "Joelhos ao peito e estenda sem tocar o chão"]],
  ["canivete_lateral", "Canivete lateral", "core", [], "core", BW, 2, false, [], ["Deitado de lado", "Suba tronco e perna ao mesmo tempo"]],
  ["infra_polia", "Abdominal infra na polia", "core", [], "core", M("polia"), 2, false, ["gestante"], ["Tornozeleira na polia baixa, deitado", "Leve os joelhos ao peito"]],
  ["rotacao_russa_polia", "Rotação na polia sentado", "core", [], "core", M("polia"), 2, false, ["lombar"], ["Sentado de lado para a polia", "Gire o tronco com os braços estendidos"]],
  ["lenhador_baixo_alto", "Lenhador de baixo para cima", "core", ["ombros"], "core", M("polia"), 1, false, ["lombar"], ["Polia baixa, puxe em diagonal até acima do ombro oposto", "Gire o tronco, braços quase retos"]],
  ["landmine_180", "Rotação com barra livre (landmine 180)", "core", ["ombros"], "core", [...BB, ...GYM], 2, false, ["lombar"], ["Segure a ponta da barra à frente", "Leve de um lado ao outro girando o tronco"]],
  ["rotacao_anilha", "Rotação com anilha", "core", [], "core", PLATES, 1, false, ["lombar"], ["Sentado, tronco inclinado para trás", "Gire levando a anilha de um lado ao outro"]],
  ["rollout_trx", "Rollout no TRX", "core", ["ombros"], "core", [["trx"]], 2, false, ["lombar", "gestante"], ["Braços estendidos nas alças", "Incline à frente levando os braços acima da cabeça"]],
  ["infra_trx", "Joelhos ao peito no TRX", "core", ["ombros"], "core", [["trx"]], 2, false, ["punho", "gestante"], ["Pés nas alças, posição de prancha", "Traga os joelhos ao peito"]],
  ["abdominal_casulo", "Abdominal casulo", "core", [], "core", BW, 1, false, ["gestante"], ["Deitado, braços acima da cabeça", "Encolha joelhos e tronco ao mesmo tempo"]],
  ["kb_oito", "Oito com kettlebell", "core", ["gluteos"], "core", KB, 2, false, ["lombar"], ["Pernas afastadas, quadril para trás", "Passe o kettlebell entre as pernas em forma de 8"]],
  ["prancha_elevacao_quadril", "Prancha com elevação de quadril", "core", ["ombros"], "core", BW, 1, false, [], ["Prancha nos antebraços", "Suba o quadril e volte à prancha"]],
  ["salto_banco", "Salto sobre o banco", "cardio", ["quadriceps"], "condicionamento", [["banco"], ["academia"]], 2, true, ["joelho", "gestante"], ["Mãos no banco, salte de um lado ao outro", "Aterrisse macio"]],
  ["salto_foguete", "Salto foguete", "cardio", ["quadriceps", "gluteos"], "condicionamento", BW, 2, true, ["joelho", "gestante", "hipertensao"], ["Agache e salte estendendo os braços para cima", "Aterrisse com joelhos flexionados"]],
  ["salto_lateral_caixa", "Salto lateral na caixa", "cardio", ["quadriceps"], "condicionamento", [["banco"], ["academia"]], 3, true, ["joelho", "gestante"], ["De lado para a caixa", "Salte de lado para cima e desça"]],
  ["shuffle_step", "Deslocamento lateral no step", "cardio", ["quadriceps"], "condicionamento", [["banco"], ["academia"]], 2, false, ["joelho"], ["Um pé no step, troque de lado passando por cima", "Ritmo rápido"], "seg"],
  ["salto_sapo", "Salto do sapo", "cardio", ["quadriceps", "gluteos"], "condicionamento", BW, 2, true, ["joelho", "gestante"], ["Agache com mãos atrás da cabeça", "Salte à frente e aterrisse agachando"]],
  ["salto_lateral_unipodal", "Saltos laterais em uma perna", "cardio", ["panturrilha"], "condicionamento", BW, 3, false, ["joelho", "gestante"], ["Numa perna só, salte de um lado ao outro", "Aterrisse com o joelho flexionado"]],
  ["simulador_escada", "Simulador de escada", "cardio", ["gluteos"], "condicionamento", [["cardio_maquina"], ["academia"]], 1, false, ["joelho"], ["Postura ereta, sem apoiar o peso nos braços", "Ritmo constante"], "seg"],
  ["empurrar_treno", "Empurrar trenó", "cardio", ["quadriceps", "gluteos"], "condicionamento", GYM, 2, true, [], ["Braços estendidos, corpo inclinado", "Passos curtos e fortes"], "seg"],
  ["marreta_pneu", "Marreta no pneu", "cardio", ["ombros", "core"], "condicionamento", GYM, 2, true, ["lombar", "ombro"], ["Pernas afastadas, marreta sobre o ombro", "Bata no pneu alternando os lados"], "seg"],
  ["virar_pneu", "Virada de pneu", "cardio", ["gluteos", "costas"], "condicionamento", GYM, 3, true, ["lombar"], ["Agache, peito no pneu", "Empurre com as pernas e vire"]],
  // ---------------- Mobilidade ----------------
  ["mob_quadril", "Mobilidade de quadril 90/90", "gluteos", [], "mobilidade", BW, 1, false, [], ["Sentado, pernas em 90°", "Gire de um lado para outro"], "seg"],
  ["mob_toracica", "Rotação torácica em quatro apoios", "costas", [], "mobilidade", BW, 1, false, [], ["Mão na nuca, gire o cotovelo para o teto"]],
  ["gato_camelo", "Gato-camelo", "costas", ["core"], "mobilidade", BW, 1, false, [], ["Arredonde e estenda a coluna devagar"]],
  ["alongamento_posterior", "Alongamento de posterior", "posterior", [], "mobilidade", BW, 1, false, [], ["Joelho estendido, incline à frente", "Respire fundo"], "seg"],
  ["deslocamento_ombro", "Deslocamento de ombro com bastão/elástico", "ombros", [], "mobilidade", BW, 1, false, [], ["Braços retos passam da frente para trás"]],
  ["agachamento_profundo", "Agachamento profundo sustentado", "quadriceps", ["gluteos"], "mobilidade", BW, 1, false, ["joelho"], ["Segure no fundo do agachamento", "Cotovelos empurram os joelhos"], "seg"],
  ["circulos_quadril_pe", "Círculos de quadril em pé", "gluteos", [], "mobilidade", BW, 1, false, [], ["Mãos na cintura, joelho sobe e gira para fora", "Círculos grandes e lentos, depois inverta"]],
  ["circulos_quadril_4apoios", "Círculos de quadril em quatro apoios", "gluteos", ["core"], "mobilidade", BW, 1, false, [], ["Em quatro apoios, tire um joelho do chão", "Desenhe um círculo grande com o joelho sem girar o tronco"]],
  ["mob_tornozelo", "Círculos de tornozelo", "panturrilha", [], "mobilidade", BW, 1, false, [], ["Pé fora do chão, gire o tornozelo", "10 para cada lado em cada pé"]],
  ["mob_joelho", "Círculos de joelho", "quadriceps", [], "mobilidade", BW, 1, false, [], ["Pés juntos, mãos nos joelhos", "Gire devagar, sem forçar"]],
  ["rotacao_ombros", "Rotação de ombros", "ombros", ["costas"], "mobilidade", BW, 1, false, [], ["Braços soltos ao lado do corpo", "Leve os ombros para cima, para trás e para baixo"]],
  ["circulos_bracos", "Círculos com os braços", "ombros", [], "mobilidade", BW, 1, false, [], ["Braços abertos na altura dos ombros", "Comece pequeno e aumente o círculo"]],
  ["circulos_cotovelo", "Círculos com os cotovelos", "ombros", ["costas"], "mobilidade", BW, 1, false, [], ["Mãos nos ombros, cotovelos na altura dos ombros", "Desenhe círculos grandes com os cotovelos"]],
  ["mob_punho", "Mobilidade de punho", "peito", [], "mobilidade", BW, 1, false, [], ["Dedos entrelaçados, gire os punhos", "Prepara os punhos para flexões e supinos"]],
  ["mob_punho_ajoelhado", "Mobilidade de punho em quatro apoios", "peito", [], "mobilidade", BW, 1, false, [], ["Palmas no chão com os dedos virados para os joelhos", "Leve o quadril para trás devagar até sentir o antebraço"], "seg"],
  ["maior_alongamento", "Maior alongamento do mundo", "gluteos", ["costas", "posterior"], "mobilidade", BW, 1, false, [], ["Afundo com a mão no chão por dentro do pé", "Gire o tronco e aponte o braço para o teto"]],
  ["minhoca", "Minhoca (inchworm)", "posterior", ["ombros", "core"], "mobilidade", BW, 1, false, ["punho"], ["Desça as mãos até o chão e caminhe até a prancha", "Volte caminhando com as mãos, joelhos o mais retos possível"]],
  ["groiner", "Groiner (afundo com cotovelo ao chão)", "gluteos", ["quadriceps"], "mobilidade", BW, 1, false, ["punho"], ["Da prancha, leve um pé ao lado da mão", "Cotovelo desce por dentro do pé e volte"]],
  ["cruz_ferro", "Cruz de ferro deitado", "gluteos", ["costas"], "mobilidade", BW, 1, false, ["lombar"], ["De bruços, braços abertos", "Leve o pé por trás do corpo em direção à mão oposta"]],
  ["rotacao_quadril_deitado", "Rotação de quadril deitado", "costas", ["gluteos"], "mobilidade", BW, 1, false, [], ["Deitado, cruze o joelho dobrado por cima do corpo", "Ombros no chão, solte a coluna na torção"], "seg"],
  ["rotacao_quadril_sentado", "Rotação de tronco sentado", "costas", ["gluteos"], "mobilidade", BW, 1, false, [], ["Sentado, cruze uma perna dobrada sobre a outra", "Gire o tronco para o lado da perna dobrada"], "seg"],
  ["bascula_ponte", "Báscula pélvica até ponte", "gluteos", ["core"], "mobilidade", BW, 1, false, ["gestante"], ["Deitado, encaixe o quadril colando a lombar no chão", "Suba vértebra por vértebra até a ponte e desça igual"]],
  ["bascula_pe", "Báscula pélvica em pé", "costas", ["core"], "mobilidade", BW, 1, false, [], ["Joelhos levemente dobrados", "Leve o quadril para frente e para trás, soltando a lombar"]],
  ["rotacao_tronco_bola", "Rotação de tronco com bola", "costas", ["core"], "mobilidade", [["bola_suica"]], 1, false, [], ["Bola à frente com braços estendidos", "Gire o tronco seguindo a bola com os olhos"]],
  ["volta_mundo_bastao", "Volta ao mundo com bastão", "ombros", ["peito"], "mobilidade", BW, 1, false, ["ombro"], ["Bastão ou cabo de vassoura com pegada bem aberta", "Leve da frente do quadril até atrás da cabeça, sem forçar"]],
  ["barra_escapular", "Barra escapular", "costas", ["ombros"], "mobilidade", PULLUP, 1, false, ["ombro"], ["Pendurado com braços estendidos", "Puxe só as escápulas para baixo, sem dobrar os cotovelos"]],
  ["rastejar_aranha", "Rastejar do homem-aranha", "gluteos", ["core", "ombros"], "mobilidade", BW, 2, false, ["punho", "ombro"], ["Posição de flexão, joelho vai até o cotovelo", "Avance alternando os lados, quadril baixo"]],
  ["carioca", "Carioca (passo cruzado lateral)", "gluteos", ["cardio"], "mobilidade", BW, 1, false, ["joelho"], ["Desloque-se de lado cruzando a perna por trás", "Gire o quadril, tronco de frente"]],
  ["flexor_quadril_pe", "Mobilidade de flexor do quadril em pé", "quadriceps", ["gluteos"], "mobilidade", BW, 1, false, [], ["Um pé à frente, calcanhar de trás fora do chão", "Empurre o quadril à frente contraindo o glúteo"], "seg"],
  ["posterior_90_90", "Posterior 90/90 deitado", "posterior", [], "mobilidade", BW, 1, false, [], ["Deitado, quadril e joelho a 90°", "Estenda o joelho para o teto e volte"]],
  ["tornozelo_parede", "Mobilidade de tornozelo na parede", "panturrilha", [], "mobilidade", BW, 1, false, [], ["Antebraços na parede, calcanhares no chão", "Aproxime o quadril da parede devagar"], "seg"],
  ["rolo_quadriceps", "Rolo no quadríceps", "quadriceps", [], "mobilidade", [["rolo"], ["academia"]], 1, false, [], ["De bruços, rolo na frente da coxa", "Role do quadril ao joelho, pare nos pontos tensos"], "seg"],
  ["rolo_posterior", "Rolo no posterior de coxa", "posterior", [], "mobilidade", [["rolo"], ["academia"]], 1, false, [], ["Sentado com o rolo embaixo das coxas", "Role do glúteo ao joelho"], "seg"],
  ["rolo_panturrilha", "Rolo na panturrilha", "panturrilha", [], "mobilidade", [["rolo"], ["academia"]], 1, false, [], ["Rolo embaixo da panturrilha, quadril fora do chão", "Cruze uma perna sobre a outra para mais pressão"], "seg"],
  ["rolo_lateral_coxa", "Rolo na lateral da coxa", "quadriceps", ["gluteos"], "mobilidade", [["rolo"], ["academia"]], 2, false, [], ["Deitado de lado sobre o rolo", "Role do quadril até perto do joelho, devagar"], "seg"],
  ["rolo_dorsal", "Rolo no dorsal", "costas", ["ombros"], "mobilidade", [["rolo"], ["academia"]], 1, false, [], ["De lado, rolo embaixo da axila", "Braço estendido acima da cabeça"], "seg"],
  ["rolo_gluteo", "Rolo no glúteo (piriforme)", "gluteos", [], "mobilidade", [["rolo"], ["academia"]], 1, false, [], ["Sentado no rolo, cruze o tornozelo sobre o joelho", "Incline para o lado da perna cruzada"], "seg"],
  ["rolo_costas_alta", "Rolo na parte alta das costas", "costas", ["ombros"], "mobilidade", [["rolo"], ["academia"]], 1, false, [], ["Rolo na altura das escápulas, braços cruzados", "Role da parte alta até o meio das costas, não na lombar"], "seg"],
  ["rolo_adutor", "Rolo na parte interna da coxa", "quadriceps", [], "mobilidade", [["rolo"], ["academia"]], 1, false, [], ["De bruços, perna aberta dobrada sobre o rolo", "Role da virilha ao joelho"], "seg"],
  ["rolo_canela", "Rolo na canela (tibial)", "panturrilha", [], "mobilidade", [["rolo"], ["academia"]], 1, false, [], ["Em quatro apoios, rolo embaixo da canela", "Role do tornozelo até abaixo do joelho"], "seg"],
];

export const EXERCISES: Exercise[] = DEFS.map(
  ([id, name, muscle, secondary, pattern, equipment, difficulty, compound, avoid, cues, unit]) => ({
    id,
    name,
    muscle,
    secondary,
    pattern,
    equipment,
    difficulty,
    compound,
    avoid,
    cues,
    unit: unit ?? "reps",
  }),
);

const BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return BY_ID.get(id);
}

/** "Academia completa" covers every piece of equipment. */
export function canDo(ex: Exercise, owned: Set<Equipment>): boolean {
  if (ex.equipment.length === 0) return true;
  if (owned.has("academia")) return true;
  return ex.equipment.some((req) => req.every((item) => owned.has(item)));
}

/** "Halteres + Banco ou Academia completa" — human description of what an exercise needs. */
export function equipmentText(ex: Exercise, labels: Record<Equipment, string>): string {
  if (ex.equipment.length === 0) return "Peso corporal";
  return ex.equipment.map((req) => req.map((e) => labels[e]).join(" + ")).join(" ou ");
}

/** Needs a gym machine (as opposed to free weights / bodyweight). */
export function isMachine(ex: Exercise, machines: Equipment[]): boolean {
  return ex.equipment.some((req) => req.some((e) => machines.includes(e) && e !== "cardio_maquina")) ||
    (ex.equipment.length === 1 && ex.equipment[0].length === 1 && ex.equipment[0][0] === "academia");
}
